Fix bugs

diff --git a/script_bootloader/usr/adguardhome/bin/adguardhome_update b/script_bootloader/usr/adguardhome/bin/adguardhome_update
--- a/script_bootloader/usr/adguardhome/bin/adguardhome_update
+++ b/script_bootloader/usr/adguardhome/bin/adguardhome_update
@@ -119,6 +119,18 @@ else
             # 下载adguardhome包
             /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
             #
+            # Check if ${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz exists
+            # 检查文件${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz是否存在
+            if [ ! -s "${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" ]
+            then
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+                #
+                /opt/bin/rm -f "${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
+                #
+                exit 5
+            fi
+            #
             # Remove previous backup
             # 删除旧备份
             /opt/bin/rm -rf "${PRIVATE_ROOT}/usr_prev"
diff --git a/script_bootloader/usr/caddy/bin/caddy_install b/script_bootloader/usr/caddy/bin/caddy_install
--- a/script_bootloader/usr/caddy/bin/caddy_install
+++ b/script_bootloader/usr/caddy/bin/caddy_install
@@ -122,6 +122,18 @@ then
         # 下载caddy
         /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -O "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" "${DOWNLOAD_LINK}"
         #
+        # Check if ${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz exists
+        # 检查文件${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz是否存在
+        if [ ! -s "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" ]
+        then
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            /opt/bin/rm -f "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
+            #
+            exit 5
+        fi
+        #
         # Create directory ${PRIVATE_USR}
         # 创建${PRIVATE_USR}目录
         /opt/bin/mkdir "${PRIVATE_USR}"
diff --git a/script_bootloader/usr/overture/bin/overture_install b/script_bootloader/usr/overture/bin/overture_install
--- a/script_bootloader/usr/overture/bin/overture_install
+++ b/script_bootloader/usr/overture/bin/overture_install
@@ -129,6 +129,18 @@ then
         # 下载overture
         /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
         #
+        # Check if ${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip exists
+        # 检查文件${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip是否存在
+        if [ ! -s "${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip" ]
+        then
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            /opt/bin/rm -f "${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip"
+            #
+            exit 5
+        fi
+        #
         # Create directory overture
         # 创建overture目录
         /opt/bin/mkdir "${PRIVATE_USR}"
diff --git a/script_bootloader/usr/syncthing/bin/syncthing_install b/script_bootloader/usr/syncthing/bin/syncthing_install
--- a/script_bootloader/usr/syncthing/bin/syncthing_install
+++ b/script_bootloader/usr/syncthing/bin/syncthing_install
@@ -118,6 +118,18 @@ then
         # 下载syncthing
         /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
         #
+        # Check if ${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz exists
+        # 检查文件${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz是否存在
+        if [ ! -s "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz" ]
+        then
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            /opt/bin/rm -f "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz"
+            #
+            exit 5
+        fi
+        #
         # Unzip syncthing package
         # 解压syncthing包
         /opt/bin/tar -xzvf "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz" -C "${PRIVATE_ROOT}"
