Release Version 16.1&16.1

diff --git a/script_bootloader/bin/drive_modifier b/script_bootloader/bin/drive_modifier
--- a/script_bootloader/bin/drive_modifier
+++ b/script_bootloader/bin/drive_modifier
@@ -8,28 +8,39 @@
 #
 ########## SET THE LABEL OF THE USB FLASH DRIVE ##########
 #
-# USB_DEVICE: USB flash drive
-# 设置自定义变量USB_DEVICE为U盘
-USB_DEVICE="$(cat "/tmp/usb.log" | sed -E -n -e 's/.*[[:space:]]+\((sd[[:alpha:]])\):[[:space:]]+Success.*/\1/p')"
+# USB_DRIVE: USB flash drive
+# 设置自定义变量USB_DRIVE为U盘
+USB_DRIVE="$(cat "/tmp/usb.log" | sed -E -n -e 's/.*[[:space:]]+\((sd[[:alpha:]])\):[[:space:]]+Success.*/\1/p' | tail -n 1)"
 #
-if [ -z "${USB_DEVICE}" ]
+if [ -z "${USB_DRIVE}" ]
 then
     echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: USB FLASH DRIVE IS NOT FOUND"
     #
     exit 1
 fi
 #
-# USB_DEVICE_PARTITION: Partition 1 of the USB flash drive
-# 设置自定义变量USB_DEVICE_PARTITION为U盘第一分区
-USB_DEVICE_PARTITION="/dev/${USB_DEVICE}1"
+# USB_DRIVE_PARTITION: Partition 1 of the USB flash drive
+# 设置自定义变量USB_DRIVE_PARTITION为U盘第一分区
+USB_DRIVE_PARTITION="/dev/${USB_DRIVE}1"
+#
+# USB_DRIVE_PARTITION_SCHEME: Partitioning scheme of the USB flash drive
+# 设置自定义变量USB_DRIVE_PARTITION_SCHEME为U盘分区方案
+USB_DRIVE_PARTITION_SCHEME="$(echo -ne "q\n" | fdisk "/dev/${USB_DRIVE}" | grep -i 'gpt')"
+#
+if [ -n "${USB_DRIVE_PARTITION_SCHEME}" ]
+then
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONVERT PARTITION SCHEME OF THE USB FLASH DRIVE FROM GPT TO MBR ON YOUR COMPUTER"
+    #
+    exit 2
+fi
 #
 # USB_DRIVE_LABEL: Default label of the USB flash drive
 # 设置自定义变量USB_DRIVE_LABEL为U盘默认卷标ASUS_ROUTER。可修改，但长度不可超过16字节
 USB_DRIVE_LABEL="ASUS_ROUTER"
 #
-# USB_DEVICE_BRAND_MODEL: Brand and model of the USB flash drive
-# 设置自定义变量USB_DEVICE_BRAND_MODEL为U盘品牌和型号
-USB_DEVICE_BRAND_MODEL="$(sed -E 's/[[:space:]]+/ /g' "/proc/scsi/sg/device_strs")"
+# USB_DRIVE_BRAND_MODEL: Brand and model of the USB flash drive
+# 设置自定义变量USB_DRIVE_BRAND_MODEL为U盘品牌和型号
+USB_DRIVE_BRAND_MODEL="$(sed -E 's/[[:space:]]+/ /g' "/proc/scsi/sg/device_strs")"
 #
 ########## END ##########
 #
@@ -40,44 +51,44 @@ cd "/tmp"
 #
 # Unmount all partitions on the USB flash drive
 # 卸载U盘上的全部分区
-MAX_PARTNUM=$(echo -ne "p\n" | fdisk "/dev/${USB_DEVICE}" | sed -E -n -e 's/[[:space:]]*\/dev\/'"${USB_DEVICE}"'([[:digit:]]+)[[:space:]]+.*/\1/p' | tail -n 1)
+MAX_PARTNUM=$(echo -ne "p\n" | fdisk "/dev/${USB_DRIVE}" | sed -E -n -e 's/[[:space:]]*\/dev\/'"${USB_DRIVE}"'([[:digit:]]+)[[:space:]]+.*/\1/p' | tail -n 1)
 #
-while [ ${MAX_PARTNUM} -gt 0 ]
+while [ -n "${MAX_PARTNUM}" ] && [ ${MAX_PARTNUM} -gt 0 ]
 do
-    umount -f "/dev/${USB_DEVICE}${MAX_PARTNUM}" 2> /dev/null
+    umount -f "/dev/${USB_DRIVE}${MAX_PARTNUM}" 2> /dev/null
     MAX_PARTNUM=$((${MAX_PARTNUM}-1))
     sleep 5
 done
 #
 sleep 10
 #
-# Re-partition /dev/${USB_DEVICE}
-# 重新分区/dev/${USB_DEVICE}
-echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: RE-PARTITION ${USB_DEVICE_BRAND_MODEL}"
-echo -ne "u\np\no\nn\np\n1\n2048\n\np\nw\n" | fdisk "/dev/${USB_DEVICE}"
+# Re-partition /dev/${USB_DRIVE}
+# 重新分区/dev/${USB_DRIVE}
+echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: RE-PARTITION ${USB_DRIVE_BRAND_MODEL}"
+echo -ne "u\np\no\nn\np\n1\n2048\n\np\nw\n" | fdisk "/dev/${USB_DRIVE}"
 #
 if [ ${?} -ne 0 ]
 then
-    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CAN'T RE-PARTITION ${USB_DEVICE_BRAND_MODEL}"
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CAN'T RE-PARTITION ${USB_DRIVE_BRAND_MODEL}"
     #
-    exit 2
+    exit 3
 fi
 #
 sleep 10
 #
-# Format ${USB_DEVICE_PARTITION} with ${USB_DRIVE_LABEL}
-# 格式化${USB_DEVICE_PARTITION}并创建卷标${USB_DRIVE_LABEL}
-echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: LABEL OF ${USB_DEVICE_BRAND_MODEL} IS ${USB_DRIVE_LABEL}"
-umount -f "/dev/${USB_DEVICE}1" 2> /dev/null
-mkfs.ext3 -FL "${USB_DRIVE_LABEL}" "${USB_DEVICE_PARTITION}"
+# Format ${USB_DRIVE_PARTITION} with ${USB_DRIVE_LABEL}
+# 格式化${USB_DRIVE_PARTITION}并创建卷标${USB_DRIVE_LABEL}
+echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: LABEL OF ${USB_DRIVE_BRAND_MODEL} IS ${USB_DRIVE_LABEL}"
+umount -f "/dev/${USB_DRIVE}1" 2> /dev/null
+mkfs.ext3 -FL "${USB_DRIVE_LABEL}" "${USB_DRIVE_PARTITION}"
 #
 # Check if mkfs.ext3 returns 0
 # 检查mkfs.ext3的返回值是否为0
 if [ ${?} -ne 0 ]
 then
-    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ${USB_DEVICE_BRAND_MODEL} IS NOT READY"
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ${USB_DRIVE_BRAND_MODEL} IS NOT READY"
     #
-    exit 3
+    exit 4
 fi
 #
 sleep 120
@@ -89,13 +100,13 @@ then
     mkdir -m 777 "/tmp/mnt/${USB_DRIVE_LABEL}"
 fi
 #
-# Mount ${USB_DEVICE_PARTITION} to /tmp/mnt/${USB_DRIVE_LABEL}
-# 挂载${USB_DEVICE_PARTITION}至/tmp/mnt/${USB_DRIVE_LABEL}
-mount "${USB_DEVICE_PARTITION}" "/tmp/mnt/${USB_DRIVE_LABEL}" 2> /dev/null
+# Mount ${USB_DRIVE_PARTITION} to /tmp/mnt/${USB_DRIVE_LABEL}
+# 挂载${USB_DRIVE_PARTITION}至/tmp/mnt/${USB_DRIVE_LABEL}
+mount "${USB_DRIVE_PARTITION}" "/tmp/mnt/${USB_DRIVE_LABEL}" 2> /dev/null
 #
 sleep 30
 #
-echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${USB_DEVICE_BRAND_MODEL} IS READY"
+echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${USB_DRIVE_BRAND_MODEL} IS READY"
 #
 exit 0
 #
diff --git a/script_bootloader/bin/install_online b/script_bootloader/bin/install_online
--- a/script_bootloader/bin/install_online
+++ b/script_bootloader/bin/install_online
@@ -10,12 +10,48 @@ SERVICE_NAME="SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER"
 # 服务功能
 SERVICE_FUNCTION="ONLINE-INSTALL"
 #
+# PUBLIC_IPV4_ADDRESS: The public IPv4 address
+# 设置自定义变量PUBLIC_IPV4_ADDRESS为公网IPv4地址
+SOURCE_OF_PUBLIC_IP_ADDRESS="whatismyip.akamai.com"
+wget -q -c -t 10 -T 120 -O "/tmp/public_ipv4_address.html" --no-check-certificate "${SOURCE_OF_PUBLIC_IP_ADDRESS}"
+#
+if [ ! -s "/tmp/public_ipv4_address.html" ] || \
+[ $(cat "/tmp/public_ipv4_address.html" | wc -c) -lt 7 ]
+then
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+    echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+    #
+    rm -f "/tmp/public_ipv4_address.html"
+    rm -f "/tmp/install_online"
+    #
+    exit 5
+else
+    PUBLIC_IPV4_ADDRESS="$(cat "/tmp/public_ipv4_address.html")"
+    rm -f "/tmp/public_ipv4_address.html"
+fi
+#
+# LOCATION: The location of the public IPv4 address
+# 设置自定义变量LOCATION为公网IPv4地址的地理位置
+SOURCE_OF_LOCATION="http://api.ipaddress.com/iptocountry?ip"
+wget -q -c -t 10 -T 120 -O "/tmp/location.html" --no-check-certificate "${SOURCE_OF_LOCATION}=${PUBLIC_IPV4_ADDRESS}"
+#
+if [ ! -s "/tmp/location.html" ] || \
+[ $(cat "/tmp/location.html" | wc -c) -lt 2 ]
+then
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+    echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+    #
+    rm -f "/tmp/location.html"
+    rm -f "/tmp/install_online"
+    #
+    exit 5
+else
+    LOCATION="$(cat "/tmp/location.html")"
+    rm -f "/tmp/location.html"
+fi
+#
 # DOWNLOAD_LINK_PREFIX: The prefix of download link of the latest SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量DOWNLOAD_LINK_PREFIX为最新版SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER的下载链接前缀
-SOURCE_OF_PUBLIC_IP_ADDRESS="whatismyip.akamai.com"
-SOURCE_OF_LOCATION="http://api.ipaddress.com/iptocountry?ip"
-PUBLIC_IPV4_ADDRESS="$(curl -s -4 "${SOURCE_OF_PUBLIC_IP_ADDRESS}")"
-LOCATION="$(curl -s -4 "${SOURCE_OF_LOCATION}=${PUBLIC_IPV4_ADDRESS}")"
 if [ "${LOCATION}" == "CN" ]
 then
     DOWNLOAD_LINK_PREFIX="https://cdn.jsdelivr.net/gh/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER@latest/script_bootloader"
@@ -148,6 +184,8 @@ then
     rm -f "/tmp/install_online"
     #
     exit 2
+else
+    rm -f "/tmp/prerequisite_checker"
 fi
 #
 ########## END ##########
@@ -182,7 +220,6 @@ do
         "n" | "no")
             echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ABORT INSTALLATION"
             #
-            rm -f "/tmp/prerequisite_checker"
             rm -f "${CURRENT_FINGERPRINT}"
             rm -f "/tmp/gohash"
             rm -f "/tmp/install_online"
@@ -213,7 +250,6 @@ then
     echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     rm -f "/tmp/drive_modifier"
-    rm -f "/tmp/prerequisite_checker"
     rm -f "${CURRENT_FINGERPRINT}"
     rm -f "/tmp/gohash"
     rm -f "/tmp/install_online"
@@ -236,11 +272,12 @@ then
     echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     rm -f "/tmp/drive_modifier"
-    rm -f "/tmp/prerequisite_checker"
     rm -f "${CURRENT_FINGERPRINT}"
     rm -f "/tmp/gohash"
     rm -f "/tmp/install_online"
     exit 4
+else
+    rm -f "/tmp/drive_modifier"
 fi
 #
 ########## END ##########
@@ -270,16 +307,15 @@ then
     echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     rm -f "/tmp/sbl_download_link.html"
-    rm -f "/tmp/drive_modifier"
-    rm -f "/tmp/prerequisite_checker"
     rm -f "${CURRENT_FINGERPRINT}"
     rm -f "/tmp/gohash"
     rm -f "/tmp/install_online"
     #
     exit 5
+else
+    DOWNLOAD_LINK="$(sed -E -n -e 's/^[[:space:]]*\"tarball_url\":[[:space:]]*\"(.*)\".*/\1/p' "/tmp/sbl_download_link.html")"
+    rm -f "/tmp/sbl_download_link.html"
 fi
-#
-DOWNLOAD_LINK="$(sed -E -n -e 's/^[[:space:]]*\"tarball_url\":[[:space:]]*\"(.*)\".*/\1/p' "/tmp/sbl_download_link.html")"
 #
 # NAME OF THE ARCHIVE
 # 设置自定义变量ARCHIVE_NAME为包文件名
@@ -308,9 +344,6 @@ then
     echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
-    rm -f "/tmp/sbl_download_link.html"
-    rm -f "/tmp/drive_modifier"
-    rm -f "/tmp/prerequisite_checker"
     rm -f "${CURRENT_FINGERPRINT}"
     rm -f "/tmp/gohash"
     rm -f "/tmp/install_online"
@@ -328,9 +361,6 @@ then
     echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
-    rm -f "/tmp/sbl_download_link.html"
-    rm -f "/tmp/drive_modifier"
-    rm -f "/tmp/prerequisite_checker"
     rm -f "${CURRENT_FINGERPRINT}"
     rm -f "/tmp/gohash"
     rm -f "/tmp/install_online"
@@ -339,6 +369,10 @@ then
 fi
 #
 sleep 30
+#
+# Remove ${ARCHIVE_NAME} package
+# 删除${ARCHIVE_NAME}包
+rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
 #
 # Move directory script_bootloader to directory ${USB_MOUNT_POINT}
 # 移动目录script_bootloader至目录${USB_MOUNT_POINT}
@@ -349,14 +383,6 @@ sleep 10
 # Remove directory JACK*
 # 删除目录JACK*
 rm -rf "${USB_MOUNT_POINT}"/JACK*
-#
-# Remove ${ARCHIVE_NAME} package
-# 删除${ARCHIVE_NAME}包
-rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
-#
-# Remove /tmp/drive_modifier
-# 删除文件/tmp/drive_modifier
-rm -f "/tmp/drive_modifier"
 #
 # Change the mode of the files
 # 更改文件权限
