Release Version 12.0&12.0

diff --git a/script_bootloader/bin/install b/script_bootloader/bin/install
--- a/script_bootloader/bin/install
+++ b/script_bootloader/bin/install
@@ -169,35 +169,6 @@ fi
 #
 sleep 10
 #
-# Check if ${SBL_SYS_USR}/entware/bin/entware_enable.service exists
-# 检查文件${SBL_SYS_USR}/entware/bin/entware_enable.service是否存在
-if [ -e "${SBL_SYS_USR}/entware/bin/entware_enable.service" ]
-then
-    # Invoke ${SBL_SYS_USR}/entware/bin/entware_enable.service
-    # 如果文件${SBL_SYS_USR}/entware/bin/entware_enable.service存在，则执行
-    ${SBL_SYS_USR}/entware/bin/entware_enable.service
-    #
-    # Check if ${SBL_SYS_USR}/entware/bin/entware_enable.service returns 1
-    # 检查文件${SBL_SYS_USR}/entware/bin/entware_enable.service的返回值是否为1
-    if [ $? == '1' ]
-    then
-        # Stop and Exit
-        # 如果返回值为1，则该程序终止
-        logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/entware/bin/entware_enable.service *****"
-        echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 9
-    fi
-    #
-else
-    # Stop and Exit
-    # 如果文件${SBL_SYS_USR}/entware/bin/entware_enable.service不存在，则该程序终止
-    logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/entware/bin/entware_enable.service *****"
-    echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 10
-fi
-#
-sleep 10
-#
 # Check if ${SBL_SYS_USR}/entware/bin/entware_install exists
 # 检查文件${SBL_SYS_USR}/entware/bin/entware_install是否存在
 if [ -e "${SBL_SYS_USR}/entware/bin/entware_install" ]
@@ -214,7 +185,7 @@ then
         # 如果返回值不为0，则该程序终止
         logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/entware/bin/entware_install *****"
         echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 11
+        exit 9
     fi
     #
 else
@@ -222,7 +193,7 @@ else
     # 如果文件${SBL_SYS_USR}/entware/bin/entware_install不存在，则该程序终止
     logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/entware/bin/entware_install *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 12
+    exit 10
 fi
 #
 sleep 10
@@ -241,7 +212,7 @@ else
     # 如果目录${USB_MOUNT_POINT}/home/root/不存在，则执行
     logger -st "($(basename $0))" $$ "***** HOME HAS NOT BEEN MOUNTED *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 13
+    exit 11
 fi
 #
 sleep 10
@@ -264,8 +235,24 @@ else
     logger -st "($(basename $0))" $$ "***** UNABLE TO LOCATE ${ENTWARE_ENVIRONMENT} *****"
     logger -st "($(basename $0))" $$ "***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 14
+    exit 12
 fi
+#
+sleep 10
+#
+# Create Public directories
+# 创建公共目录
+mkdir ${USB_MOUNT_POINT}/www
+logger -st "($(basename $0))" $$ "***** PUBLIC DIRECTORIES HAVE BEEN CREATED *****"
+#
+# Create Personal directories
+# 创建私有目录
+mkdir ${USB_MOUNT_POINT}/home/root/Documents
+mkdir ${USB_MOUNT_POINT}/home/root/Downloads
+mkdir ${USB_MOUNT_POINT}/home/root/Music
+mkdir ${USB_MOUNT_POINT}/home/root/Pictures
+mkdir ${USB_MOUNT_POINT}/home/root/Videos
+logger -st "($(basename $0))" $$ "***** PERSONAL DIRECTORIES HAVE BEEN CREATED *****"
 #
 sleep 10
 #
@@ -285,7 +272,7 @@ then
         # 如果返回值不为0，则该程序终止
         logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/timezone/bin/timezone_install *****"
         echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 15
+        exit 13
     fi
     #
 else
@@ -293,7 +280,7 @@ else
     # 如果文件${SBL_SYS_USR}/timezone/bin/timezone_install不存在，则该程序终止
     logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/timezone/bin/timezone_install *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 16
+    exit 14
 fi
 #
 sleep 10
@@ -314,7 +301,7 @@ then
         # 如果返回值不为0，则该程序终止
         logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/timezone/bin/timezone_enable.service *****"
         echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 17
+        exit 15
     fi
     #
 else
@@ -322,65 +309,65 @@ else
     # 如果文件${SBL_SYS_USR}/timezone/bin/timezone_enable.service不存在，则该程序终止
     logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/timezone/bin/timezone_enable.service *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
+    exit 16
+fi
+#
+sleep 10
+#
+# Check if ${SBL_SYS_USR}/dependency/bin/dependency_install exists
+# 检查文件${SBL_SYS_USR}/dependency/bin/dependency_install是否存在
+if [ -e "${SBL_SYS_USR}/dependency/bin/dependency_install" ]
+then
+    # Invoke ${SBL_SYS_USR}/dependency/bin/dependency_install
+    # 如果文件${SBL_SYS_USR}/dependency/bin/dependency_install存在，则执行
+    ${SBL_SYS_USR}/dependency/bin/dependency_install
+    #
+    # Check if ${SBL_SYS_USR}/dependency/bin/dependency_install returns 0
+    # 检查文件${SBL_SYS_USR}/dependency/bin/dependency_install的返回值是否为0
+    if [ $? != '0' ]
+    then
+        # Stop and Exit
+        # 如果返回值不为0，则该程序终止
+        logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/dependency/bin/dependency_install *****"
+        echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
+        exit 17
+    fi
+    #
+else
+    # Stop and Exit
+    # 如果文件${SBL_SYS_USR}/dependency/bin/dependency_install不存在，则该程序终止
+    logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/dependency/bin/dependency_install *****"
+    echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
     exit 18
 fi
 #
 sleep 10
 #
-# Check if ${SBL_SYS_USR}/development_tools/bin/development_tools_install exists
-# 检查文件${SBL_SYS_USR}/development_tools/bin/development_tools_install是否存在
-if [ -e "${SBL_SYS_USR}/development_tools/bin/development_tools_install" ]
+# Check if ${SBL_SYS_USR}/dependency/bin/dependency_enable.service exists
+# 检查文件${SBL_SYS_USR}/dependency/bin/dependency_enable.service是否存在
+if [ -e "${SBL_SYS_USR}/dependency/bin/dependency_enable.service" ]
 then
-    # Invoke ${SBL_SYS_USR}/development_tools/bin/development_tools_install
-    # 如果文件${SBL_SYS_USR}/development_tools/bin/development_tools_install存在，则执行
-    ${SBL_SYS_USR}/development_tools/bin/development_tools_install
+    # Invoke ${SBL_SYS_USR}/dependency/bin/dependency_enable.service
+    # 如果文件${SBL_SYS_USR}/dependency/bin/dependency_enable.service存在，则执行
+    ${SBL_SYS_USR}/dependency/bin/dependency_enable.service
     #
-    # Check if ${SBL_SYS_USR}/development_tools/bin/development_tools_install returns 0
-    # 检查文件${SBL_SYS_USR}/development_tools/bin/development_tools_install的返回值是否为0
+    # Check if ${SBL_SYS_USR}/dependency/bin/dependency_enable.service returns 0
+    # 检查文件${SBL_SYS_USR}/dependency/bin/dependency_enable.service的返回值是否为0
     if [ $? != '0' ]
     then
         # Stop and Exit
         # 如果返回值不为0，则该程序终止
-        logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/development_tools/bin/development_tools_install *****"
+        logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/dependency/bin/dependency_enable.service *****"
         echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
         exit 19
     fi
     #
 else
     # Stop and Exit
-    # 如果文件${SBL_SYS_USR}/development_tools/bin/development_tools_install不存在，则该程序终止
-    logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/development_tools/bin/development_tools_install *****"
+    # 如果文件${SBL_SYS_USR}/dependency/bin/dependency_enable.service不存在，则该程序终止
+    logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/dependency/bin/dependency_enable.service *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
     exit 20
-fi
-#
-sleep 10
-#
-# Check if ${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service exists
-# 检查文件${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service是否存在
-if [ -e "${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service" ]
-then
-    # Invoke ${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service
-    # 如果文件${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service存在，则执行
-    ${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service
-    #
-    # Check if ${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service returns 0
-    # 检查文件${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service的返回值是否为0
-    if [ $? != '0' ]
-    then
-        # Stop and Exit
-        # 如果返回值不为0，则该程序终止
-        logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service *****"
-        echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 21
-    fi
-    #
-else
-    # Stop and Exit
-    # 如果文件${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service不存在，则该程序终止
-    logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service *****"
-    echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 22
 fi
 #
 sleep 10
@@ -401,7 +388,7 @@ then
         # 如果返回值不为0，则该程序终止
         logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/monit/bin/monit_install *****"
         echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 23
+        exit 21
     fi
     #
 else
@@ -409,7 +396,7 @@ else
     # 如果文件${SBL_SYS_USR}/monit/bin/monit_install不存在，则该程序终止
     logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/monit/bin/monit_install *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 24
+    exit 22
 fi
 #
 sleep 10
@@ -436,7 +423,7 @@ then
         # 如果返回值不为0，则该程序终止
         logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/dnsmasq.d/bin/dnsmasq.d_install *****"
         echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 25
+        exit 23
     fi
     #
 else
@@ -444,7 +431,7 @@ else
     # 如果文件${SBL_SYS_USR}/dnsmasq.d/bin/dnsmasq.d_install不存在，则该程序终止
     logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/dnsmasq.d/bin/dnsmasq.d_install *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 26
+    exit 24
 fi
 #
 sleep 10
@@ -465,7 +452,7 @@ then
         # 如果返回值不为0，则该程序终止
         logger -st "($(basename $0))" $$ "***** ERROR: ${SBL_SYS_USR}/dnsmasq.d/bin/dnsmasq.d_enable.service *****"
         echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-        exit 27
+        exit 25
     fi
     #
 else
@@ -473,7 +460,7 @@ else
     # 如果文件${SBL_SYS_USR}/dnsmasq.d/bin/dnsmasq.d_enable.service不存在，则该程序终止
     logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_USR}/dnsmasq.d/bin/dnsmasq.d_enable.service *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 28
+    exit 26
 fi
 #
 sleep 10
@@ -486,7 +473,7 @@ then
     #
     # Modify ${SBL_SYS_BIN}/list_of_user_custom_scripts
     # 修改文件${SBL_SYS_BIN}/list_of_user_custom_scripts
-    ${USB_MOUNT_POINT}/bin/sed -i -e '/# NEXT SERVICE/i\# DEVELOPMENT-TOOLS SERVICE\n${SBL_SYS_USR}/development_tools/bin/development_tools_enable.service\n#' ${SBL_SYS_BIN}/list_of_user_custom_scripts
+    ${USB_MOUNT_POINT}/bin/sed -i -e '/# NEXT SERVICE/i\# DEPENDENCY SERVICE\n${SBL_SYS_USR}/dependency/bin/dependency_enable.service\n#' ${SBL_SYS_BIN}/list_of_user_custom_scripts
     #
     ${USB_MOUNT_POINT}/bin/sed -i -e '/# NEXT SERVICE/i\# DNSMASQ.D SERVICE\n${SBL_SYS_USR}/dnsmasq.d/bin/dnsmasq.d_enable.service\n#' ${SBL_SYS_BIN}/list_of_user_custom_scripts
     #
@@ -495,7 +482,7 @@ else
     # 如果文件${SBL_SYS_BIN}/list_of_user_custom_scripts不存在，则该程序终止
     logger -st "($(basename $0))" $$ "***** ERROR: CAN'T LOCATE ${SBL_SYS_BIN}/list_of_user_custom_scripts *****"
     echo -e "\033[1;41;37m***** STAGE 2: FAILED *****\033[0m"
-    exit 30
+    exit 27
 fi
 #
 sleep 10
diff --git a/script_bootloader/usr/entware/bin/entware_install b/script_bootloader/usr/entware/bin/entware_install
--- a/script_bootloader/usr/entware/bin/entware_install
+++ b/script_bootloader/usr/entware/bin/entware_install
@@ -16,9 +16,17 @@ ROUTER_MODEL=$(nvram get model)
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
 USB_MOUNT_POINT=$(nvram get script_usbmount | sed 's/\/script_bootloader.*//')
 #
-# SBL_SITE: The directory which contains all the sites
-# 设置自定义变量SBL_SITE为站点目录
-SBL_SITE=${USB_MOUNT_POINT}/www
+# SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
+# 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
+SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+#
+# PRIVATE_ROOT: The root directory for this program
+# 设置自定义变量PRIVATE_ROOT为此程序根目录
+PRIVATE_ROOT=${SBL_SYS_USR}/entware
+#
+# PRIVATE_ETC: The directory which contains all the configuration files related to this program
+# 设置自定义变量PRIVATE_ETC为此程序配置文件目录
+PRIVATE_ETC=${PRIVATE_ROOT}/etc
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -27,6 +35,10 @@ SERVICE_NAME="ENTWARE"
 # FUNCTION OF THE SERVICE
 # 服务功能
 SERVICE_FUNCTION="INSTALLATION"
+#
+# FILES_TO_COPY: The list of files that should be copied
+# 设置自定义变量FILES_TO_COPY为待复制文件列表
+FILES_TO_COPY="${PRIVATE_ETC}/files_to_copy.autosave"
 #
 ########## END ##########
 #
@@ -38,11 +50,48 @@ logger -st "($(basename $0))" $$ "*--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} 
 ########## END ##########
 #
 #
-########## INSTALLATION CONFIGURATION ##########
+########## PREPARE ENVIRONMENT ##########
 #
-# Check the architecture of the ASUS Router
-# 检查华硕路由器架构
-ROUTER_ARCHITECTURE=$(uname -m)
+# Take the appropriate way to make /opt available according to the type of /opt
+# 根据/opt的类型，采用适当方法使目录/opt可用
+if [ -L "/opt" ]
+then
+    # OPT_TARGET: The target of the symbolic link /opt
+    # 设置自定义变量OPT_TARGET为符号链接文件/opt的目标
+    OPT_TARGET=$(ls -al /opt | awk -F ' ' '{print $11}' | sed 's/^/\//')
+    #
+    # Create symbolic link file ${OPT_TARGET}
+    # 创建符号链接文件${OPT_TARGET}
+    ln -sf ${USB_MOUNT_POINT} ${OPT_TARGET}
+    #
+    sleep 5
+    #
+elif [ -d "/opt" ]
+then
+    # If it is a directory, then copy all files except symbolic link files in /opt to ${USB_MOUNT_POINT} and mount ${USB_MOUNT_POINT} to /opt
+    # 如果是目录，则将目录/opt下全部非符号链接文件复制至目录${USB_MOUNT_POINT}，之后挂载目录${USB_MOUNT_POINT}至目录/opt
+    #
+    mkdir ${PRIVATE_ETC}
+    ls -al /opt/ | grep -ve '^l.*' | tail -n +3 | awk -F ' ' '{print $9}' > ${FILES_TO_COPY}
+    sed -i "s/^/\/opt\//" ${FILES_TO_COPY}
+    cp -r $(cat ${FILES_TO_COPY}) ${USB_MOUNT_POINT}
+    logger -st "($(basename $0))" $$ "***** FILES IN /opt HAVE BEEN COPIED *****"
+    #
+    # Mount the USB flash drive to /opt
+    # 挂载U盘至目录/opt
+    mount ${USB_MOUNT_POINT} /opt
+    #
+    sleep 5
+    #
+else
+    # Do nothing but prompt the user
+    # 如果/opt的类型不符合上述两种情况，则执行
+    logger -st "($(basename $0))" $$ "***** TYPE OF /opt IS UNKNOWN *****"
+    logger -st "($(basename $0))" $$ "***** ENVIRONMENT FOR ENTWARE CAN'T BE SET *****"
+    logger -st "($(basename $0))" $$ "***** ${SERVICE_NAME}_${SERVICE_FUNCTION} SERVICE HAS NOT BEEN LOADED *****"
+    #
+    exit 1
+fi
 #
 ########## END ##########
 #
@@ -51,28 +100,28 @@ ROUTER_ARCHITECTURE=$(uname -m)
 #
 # Install Entware according to the architecture of the ASUS Router
 # 根据路由器架构，自动安装适当版本的Entware
-if [ ${ROUTER_ARCHITECTURE} == "aarch64" ]
-then
-    wget -O - http://bin.entware.net/aarch64-k3.10/installer/generic.sh | sh
-    logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
-    #
-elif [ ${ROUTER_ARCHITECTURE} == "armv7l" ]
-then
-    wget -O - http://bin.entware.net/armv7sf-k2.6/installer/generic.sh | sh
-    logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
-    #
-elif [ ${ROUTER_ARCHITECTURE} == "mips" ]
-then
-    wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | sh
-    logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
-    #
-else
-    # Do nothing but prompt the user
-    # 如果路由器架构不符合上述三种情况，则执行
-    logger -st "($(basename $0))" $$ "***** ROUTER ARCHITECTURE IS UNKNOWN *****"
-    logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
-    exit 1
-fi
+case $(uname -m) in
+    "aarch64")
+        wget -O - http://bin.entware.net/aarch64-k3.10/installer/generic.sh | sh
+        logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        ;;
+    "armv7l")
+        wget -O - http://bin.entware.net/armv7sf-k2.6/installer/generic.sh | sh
+        logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        ;;
+    "mips")
+        wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | sh
+        logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        ;;
+    *)
+        # Do nothing but prompt the user
+        # 如果路由器架构不符合上述三种情况，则执行
+        logger -st "($(basename $0))" $$ "***** ROUTER ARCHITECTURE IS UNKNOWN *****"
+        logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+        #
+        exit 2
+        ;;
+esac
 #
 ########## END ##########
 #
@@ -87,36 +136,17 @@ if [ ! -d "${USB_MOUNT_POINT}/home/root/" ]
 then
     # Copy /tmp/home/root to ${USB_MOUNT_POINT}/home/
     # 如果目录${USB_MOUNT_POINT}/home/root/不存在，则执行
-    cp -R /tmp/home/root ${USB_MOUNT_POINT}/home/
+    cp -r /tmp/home/root ${USB_MOUNT_POINT}/home/
     logger -st "($(basename $0))" $$ "***** HOME HAS BEEN COPIED *****"
+    #
+    exit 0
     #
 else
     # Do nothing but prompt the user
     # 如果目录${USB_MOUNT_POINT}/home/root/存在，则执行
     logger -st "($(basename $0))" $$ "***** HOME EXISTS *****"
-fi
-#
-########## END ##########
-#
-#
-########## CREATE DIRECTORY ${SBL_SITE} ##########
-#
-logger -st "($(basename $0))" $$ "***** CREATE DIRECTORY ${SBL_SITE} *****"
-#
-# Check if directory ${SBL_SITE} exists
-# 检查目录${SBL_SITE}是否存在
-if [ ! -d "${SBL_SITE}" ]
-then
-    # Create directory ${SBL_SITE}
-    # 如果目录${SBL_SITE}不存在，则执行
-    mkdir ${SBL_SITE}
     #
-    logger -st "($(basename $0))" $$ "***** ${SBL_SITE} HAS BEEN CREATED *****"
-    #
-else
-    # Do nothing but prompt the user
-    # 如果目录${SBL_SITE}存在，则执行
-    logger -st "($(basename $0))" $$ "***** ${SBL_SITE} EXISTS *****"
+    exit 0
 fi
 #
 ########## END ##########
