Add auto_update

diff --git a/script_bootloader/bin/install b/script_bootloader/bin/install
--- a/script_bootloader/bin/install
+++ b/script_bootloader/bin/install
@@ -631,6 +631,36 @@ fi
 #
 sleep 10
 #
+# Check if ${SBL_SYS_USR}/auto_update/bin/auto_update_install exists
+# 检查文件${SBL_SYS_USR}/auto_update/bin/auto_update_install是否存在
+if [ -e "${SBL_SYS_USR}/auto_update/bin/auto_update_install" ]
+then
+    # Invoke ${SBL_SYS_USR}/auto_update/bin/auto_update_install
+    # 如果文件${SBL_SYS_USR}/auto_update/bin/auto_update_install存在，则执行
+    "${SBL_SYS_USR}/auto_update/bin/auto_update_install"
+    #
+    # Check if ${SBL_SYS_USR}/auto_update/bin/auto_update_install returns 0
+    # 检查文件${SBL_SYS_USR}/auto_update/bin/auto_update_install的返回值是否为0
+    if [ ${?} -ne 0 ]
+    then
+        # Stop and Exit
+        # 如果返回值不为0，则该程序终止
+        echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: STAGE 2"
+        #
+        exit 29
+    fi
+    #
+else
+    # Stop and Exit
+    # 如果文件${SBL_SYS_USR}/auto_update/bin/auto_update_install不存在，则该程序终止
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CAN'T LOCATE ${SBL_SYS_USR}/auto_update/bin/auto_update_install"
+    echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: STAGE 2"
+    #
+    exit 30
+fi
+#
+sleep 10
+#
 # Check if ${SBL_SYS_BIN}/list_of_user_custom_scripts exists
 # 检查文件${SBL_SYS_BIN}/list_of_user_custom_scripts是否存在
 if [ -e "${SBL_SYS_BIN}/list_of_user_custom_scripts" ]
@@ -647,7 +677,7 @@ else
     echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CAN'T LOCATE ${SBL_SYS_BIN}/list_of_user_custom_scripts"
     echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: STAGE 2"
     #
-    exit 29
+    exit 31
 fi
 #
 sleep 10
@@ -672,7 +702,7 @@ done
 # 临时解决方案：以下4行代码的存在是因为gotee不能输出没有\n的行，导致不显示插件安装提示信息
 if ${TEST_FMW_TEE}
 then
-    exit 30
+    exit 32
 fi
 #
 # Check if ${SBL_SYS_BIN}/addons_install exists
