Update install_online

diff --git a/script_bootloader/bin/install_online b/script_bootloader/bin/install_online
--- a/script_bootloader/bin/install_online
+++ b/script_bootloader/bin/install_online
@@ -21,12 +21,29 @@ chmod 777 /tmp/prerequisite_checker
 # 执行/tmp/prerequisite_checker
 /tmp/prerequisite_checker
 #
-if [ ${?} -ne 0 ]
-then
-    echo -e "\033[1;41;37m***** ERROR: MISSING PREREQUISITES *****\033[0m"
-    echo -e "Abort installation ..."
-    exit 1
-fi
+case ${?} in
+    1)
+        echo -e "\033[1;41;37m***** ERROR: MISSING ESSENTIAL COMMANDS *****\033[0m"
+        echo -e "Abort installation ..."
+        exit 1
+        ;;
+    2)
+        echo -e "\033[1;41;37m***** ERROR: MISSING ESSENTIAL FILES *****\033[0m"
+        echo -e "Abort installation ..."
+        exit 1
+        ;;
+    3)
+        echo -e "\033[1;41;37m***** ERROR: MISSING ESSENTIAL FEATURES *****\033[0m"
+        echo -e "Abort installation ..."
+        exit 1
+        ;;
+    4)
+        echo -e "\033[1;41;37m***** ERROR: MISSING ESSENTIAL SETTINGS *****\033[0m"
+        echo -e "Modify settings as instructions above, reboot the router and then try again."
+        echo -e "Abort installation ..."
+        exit 1
+        ;;
+esac
 #
 ########## END ##########
 #
