Update upgrade

diff --git a/script_bootloader/bin/upgrade b/script_bootloader/bin/upgrade
--- a/script_bootloader/bin/upgrade
+++ b/script_bootloader/bin/upgrade
@@ -68,27 +68,38 @@ SOURCE_DIRECTORY="${USB_MOUNT_POINT}"
 # 设置自定义变量EXCLUDED_DIRECTORY为被排除目录
 EXCLUDED_DIRECTORY="${USB_MOUNT_POINT}/home"
 #
-# DOWNLOAD_LINK: Download link of the latest SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
-# 设置自定义变量DOWNLOAD_LINK为最新版SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER的下载链接
-wget -q -c -t 10 -T 120 -O "/tmp/sbl_download_link.html" --no-check-certificate "https://api.github.com/repos/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/releases/latest"
-#
-if [ ! -s "/tmp/sbl_download_link.html" ] || \
-[ $(cat "/tmp/sbl_download_link.html" | wc -l) -lt 20 ]
-then
-    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
-    echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
-    #
-    rm -f "/tmp/sbl_download_link.html"
-    #
-    exit 5
-else
-    DOWNLOAD_LINK="$(sed -E -n -e 's/^[[:space:]]*\"tarball_url\":[[:space:]]*\"(.*)\".*/\1/p' "/tmp/sbl_download_link.html")"
-    rm -f "/tmp/sbl_download_link.html"
-fi
-#
 # NAME OF THE ARCHIVE
 # 设置自定义变量ARCHIVE_NAME为包文件名
 ARCHIVE_NAME="sbl_setup.tar.gz"
+#
+# Check if ${EXCLUDED_DIRECTORY}/root/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*.tar.gz exists
+# 检查文件${EXCLUDED_DIRECTORY}/root/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*.tar.gz是否存在
+if [ -e "${EXCLUDED_DIRECTORY}/root"/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*.tar.gz ]
+then
+    UPGRADE_ONLINE="false"
+    #
+    mv -f "${EXCLUDED_DIRECTORY}/root"/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*.tar.gz "${ARCHIVE_NAME}"
+else
+    UPGRADE_ONLINE="true"
+    #
+    # DOWNLOAD_LINK: Download link of the latest SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
+    # 设置自定义变量DOWNLOAD_LINK为最新版SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER的下载链接
+    wget -q -c -t 10 -T 120 -O "/tmp/sbl_download_link.html" --no-check-certificate "https://api.github.com/repos/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/releases/latest"
+    #
+    if [ ! -s "/tmp/sbl_download_link.html" ] || \
+    [ $(cat "/tmp/sbl_download_link.html" | wc -l) -lt 20 ]
+    then
+        echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+        echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        rm -f "/tmp/sbl_download_link.html"
+        #
+        exit 5
+    else
+        DOWNLOAD_LINK="$(sed -E -n -e 's/^[[:space:]]*\"tarball_url\":[[:space:]]*\"(.*)\".*/\1/p' "/tmp/sbl_download_link.html")"
+        rm -f "/tmp/sbl_download_link.html"
+    fi
+fi
 #
 # OPERATING_SYSTEM: Operating system of the ASUS Router
 # 设置自定义变量OPERATING_SYSTEM为华硕路由器系统
@@ -154,57 +165,86 @@ done
 #
 echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: INSTALL LATEST ${SERVICE_NAME}"
 #
-# Remove vestigial ${ARCHIVE_NAME} package
-# 删除遗留的${ARCHIVE_NAME}包
-rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
-#
-# Download ${ARCHIVE_NAME} package
-# 下载${ARCHIVE_NAME}包
-wget -q -c -t 10 -T 120 -O "${USB_MOUNT_POINT}/${ARCHIVE_NAME}" --no-check-certificate "${DOWNLOAD_LINK}"
-#
-sleep 30
-#
-# Check if ${USB_MOUNT_POINT}/${ARCHIVE_NAME} exists
-# 检查文件${USB_MOUNT_POINT}/${ARCHIVE_NAME}是否存在
-if [ ! -s "${USB_MOUNT_POINT}/${ARCHIVE_NAME}" ]
+if ${UPGRADE_ONLINE}
 then
-    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
-    echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+    # Download ${ARCHIVE_NAME} package
+    # 下载${ARCHIVE_NAME}包
+    wget -q -c -t 10 -T 120 -O "${USB_MOUNT_POINT}/${ARCHIVE_NAME}" --no-check-certificate "${DOWNLOAD_LINK}"
     #
-    rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
+    sleep 30
     #
-    exit 5
+    # Check if ${USB_MOUNT_POINT}/${ARCHIVE_NAME} exists
+    # 检查文件${USB_MOUNT_POINT}/${ARCHIVE_NAME}是否存在
+    if [ ! -s "${USB_MOUNT_POINT}/${ARCHIVE_NAME}" ]
+    then
+        echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+        echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
+        #
+        exit 5
+    fi
+    #
+    # Untar ${ARCHIVE_NAME} package
+    # 解压${ARCHIVE_NAME}包
+    tar -xzvf "${USB_MOUNT_POINT}/${ARCHIVE_NAME}" -C "${USB_MOUNT_POINT}" > /dev/null 2>&1
+    #
+    if [ ${?} -ne 0 ]
+    then
+        echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ${ARCHIVE_NAME} IS CORRUPT"
+        echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
+        #
+        exit 5
+    fi
+    #
+    sleep 30
+    #
+    # Move directory script_bootloader to directory ${USB_MOUNT_POINT}
+    # 移动目录script_bootloader至目录${USB_MOUNT_POINT}
+    mv -f "${USB_MOUNT_POINT}"/JACK*/script_bootloader "${USB_MOUNT_POINT}"
+    #
+    sleep 10
+    #
+    # Remove directory JACK*
+    # 删除目录JACK*
+    rm -rf "${USB_MOUNT_POINT}"/JACK*
+    #
+else
+    mv -f "${EXCLUDED_DIRECTORY}/root"/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*.tar.gz "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
+    #
+    # Untar ${ARCHIVE_NAME} package
+    # 解压${ARCHIVE_NAME}包
+    tar -xzvf "${USB_MOUNT_POINT}/${ARCHIVE_NAME}" -C "${USB_MOUNT_POINT}" > /dev/null 2>&1
+    #
+    if [ ${?} -ne 0 ]
+    then
+        echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ${ARCHIVE_NAME} IS CORRUPT"
+        echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
+        #
+        exit 5
+    fi
+    #
+    sleep 30
+    #
+    # Move directory script_bootloader to directory ${USB_MOUNT_POINT}
+    # 移动目录script_bootloader至目录${USB_MOUNT_POINT}
+    mv -f "${USB_MOUNT_POINT}"/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*/script_bootloader "${USB_MOUNT_POINT}"
+    #
+    sleep 10
+    #
+    # Remove directory SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*
+    # 删除目录SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*
+    rm -rf "${USB_MOUNT_POINT}"/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER*
+    #
 fi
-#
-# Untar ${ARCHIVE_NAME} package
-# 解压${ARCHIVE_NAME}包
-tar -xzvf "${USB_MOUNT_POINT}/${ARCHIVE_NAME}" -C "${USB_MOUNT_POINT}" > /dev/null 2>&1
-#
-if [ ${?} -ne 0 ]
-then
-    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ${ARCHIVE_NAME} IS CORRUPT"
-    echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
-    #
-    rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
-    #
-    exit 5
-fi
-#
-sleep 30
 #
 # Remove ${ARCHIVE_NAME} package
 # 删除${ARCHIVE_NAME}包
 rm -f "${USB_MOUNT_POINT}/${ARCHIVE_NAME}"
-#
-# Move directory script_bootloader to directory ${USB_MOUNT_POINT}
-# 移动目录script_bootloader至目录${USB_MOUNT_POINT}
-mv -f "${USB_MOUNT_POINT}"/JACK*/script_bootloader "${USB_MOUNT_POINT}"
-#
-sleep 10
-#
-# Remove directory JACK*
-# 删除目录JACK*
-rm -rf "${USB_MOUNT_POINT}"/JACK*
 #
 # Change the mode of the files
 # 更改文件权限
