New Release

diff --git a/script_bootloader/script_bootloader_usb_mount b/script_bootloader/script_bootloader_usb_mount
--- a/script_bootloader/script_bootloader_usb_mount
+++ b/script_bootloader/script_bootloader_usb_mount
@@ -7,19 +7,47 @@ logger -st "($(basename $0))" $$ "***** BOOTING UP ASUS ROUTER (300 SECONDS) ***
 # Waiting 300s
 #sleep 300
 #
-########## CHECK THE TYPE OF FIRMWARE ##########
+########## CHECK ASUS ROUTER STATUS ##########
 #
-if [ -z $(nvram show | grep -e '.*merlin.*') ]
+# Check if the router is ready for running user's custom scripts
+# 检查路由器是否已经准备好执行用户自定义脚本
+#
+# Check it out every 30 seconds in 5 minutes
+# 每30秒检查1次，最多执行10次，最多用时5分钟
+i=1
+while [ ${i} -le 10 ]
+do
+    success_start_service=$(nvram get success_start_service)
+    if [ "${success_start_service}" == "1" ]
+    then
+        logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS READY *****"
+        break
+    fi
+    i=$((${i}+1))
+    logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS NOT READY, WAIT 30 SECONDS MORE *****"
+    sleep 30
+done
+#
+# Stop and Exit
+# 如果10次检查均为路由器没准备好执行脚本，则该脚本终止
+if [ "${success_start_service}" != "1" ]
 then
-    # ASUSWRT
-    logger -st "($(basename $0))" $$ "***** FIRMWARE: ASUSWRT *****"
-    ROUTER_TYPE='ASUSWRT'
-    #
-else
-    # ASUS_MERLIN
-    logger -st "($(basename $0))" $$ "***** FIRMWARE: ASUS MERLIN *****"
-    ROUTER_TYPE='ASUS_MERLIN'
+    logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS NOT READY *****"
+    logger -st "($(basename $0))" $$ "***** EXIT *****"
+    exit 1
 fi
+#
+########## END ##########
+#
+#
+########## SET THE CUSTOM VARIABLES ##########
+#
+# 设置自定义变量
+# 当该程序运行结束，此处设置的变量自动取消
+#
+# USB_PATH: The mount point of the USB flash drive
+# 设置自定义变量USB_PATH为U盘挂载点
+USB_PATH=$(nvram get script_usbmount | awk -F / '{print "/"$2"/"$3"/"$4}')
 #
 ########## END ##########
 #
@@ -33,64 +61,59 @@ cd /tmp/
 ########## END ##########
 #
 #
-########## CHECK THE DEVICE NAME FOR THE LABEL ASUS_ROUTER ##########
+########## CHECK THE TYPE OF FIRMWARE ##########
 #
-DEV_NAME=$(blkid | grep -e 'ASUS_ROUTER' | cut -d ':' -f 1)
-#
-########## END ##########
-#
-#
-########## CHECK ASUS ROUTER STATUS ##########
-#
-# Check if the router is ready for running user's custom scripts
-# 检查路由器是否已经准备好执行用户自定义脚本
-#
-# Check it out every 30 seconds in 5 minutes
-# 每30秒检查1次，最多执行10次，最多用时5分钟
-i=1
-while [ $i -le 10 ]
-do
-    success_start_service=`nvram get success_start_service`
-    if [ "$success_start_service" == "1" ]
-    then
-        logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS READY *****"
-        break
-    fi
-    i=$(($i+1))
-    logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS NOT READY, WAIT 30 SECONDS MORE *****"
-    sleep 30
-done
-#
-# Stop and Exit
-# 如果10次检查均为路由器没准备好执行脚本，则该脚本终止
-if [ "$success_start_service" != "1" ]
+if [ -z $(nvram show | grep -e '.*merlin.*') ]
 then
-    logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS NOT READY *****"
-    logger -st "($(basename $0))" $$ "***** EXIT *****"
-    exit 1
+    # ASUSWRT
+    logger -st "($(basename $0))" $$ "***** FIRMWARE: ASUSWRT *****"
+    ROUTER_TYPE="ASUSWRT"
+    #
+else
+    # ASUS_MERLIN
+    logger -st "($(basename $0))" $$ "***** FIRMWARE: ASUS MERLIN *****"
+    ROUTER_TYPE="ASUS_MERLIN"
 fi
 #
 ########## END ##########
 #
 #
-########## LOCATE AND LOAD THE LIST OF USER'S CUSTOM SCRIPTS ##########
+########## CHECK THE DEVICE NAME FOR THE LABEL ASUS_ROUTER ##########
 #
-# Check if /tmp/mnt/ASUS_ROUTER/script_bootloader/user_scripts/list_of_user_custom_scripts exists
-# 检查用户自定义脚本列表（本例中，该脚本为/tmp/mnt/ASUS_ROUTER/script_bootloader/user_scripts/list_of_user_custom_scripts）是否存在
-if [ -e "/tmp/mnt/ASUS_ROUTER/script_bootloader/user_scripts/list_of_user_custom_scripts" ]
+DEV_NAME=$(df | grep -e ".*${USB_PATH}.*" | awk '{print $1}')
+#
+########## END ##########
+#
+#
+########## MOUNT HOME ##########
+#
+# Check if ${USB_PATH}/home/root/ exists
+# 检查目录${USB_PATH}/home/root/是否存在
+if [ -d "${USB_PATH}/home/root/" ]
 then
-    logger -st "($(basename $0))" $$ "***** LIST OF USER'S CUSTOM SCRIPTS EXISTS *****"
-    # Load user's custom scripts
-    # 如果用户自定义脚本列表存在，则执行该脚本
-    logger -st "($(basename $0))" $$ "***** LOAD THE LIST OF USER'S CUSTOM SCRIPTS *****"
-    /tmp/mnt/ASUS_ROUTER/script_bootloader/user_scripts/list_of_user_custom_scripts
+    # Mount ${USB_PATH}/home/ to /tmp/home/
+    # 如果目录${USB_PATH}/home/root/存在，则执行
+    mount ${USB_PATH}/home/ /tmp/home/
+    logger -st "($(basename $0))" $$ "***** HOME HAS BEEN MOUNTED *****"
     #
 else
-    # Stop and Exit
-    # 如果用户自定义脚本列表不存在，则该脚本终止
-    logger -st "($(basename $0))" $$ "***** UNABLE TO LOCATE THE LIST OF USER'S CUSTOM SCRIPTS *****"
-    logger -st "($(basename $0))" $$ "***** EXIT *****"
-    exit 2
+    # Do nothing but prompt the user
+    # 如果目录${USB_PATH}/home/root/不存在，则执行
+    logger -st "($(basename $0))" $$ "***** HOME HAS NOT BEEN MOUNTED *****"
+fi
+#
+########## END ##########
+#
+#
+########## ENABLE SWAPFILE ##########
+#
+# Check if ${USB_PATH}/script_bootloader/user_scripts/swap/swap_enable.service exists
+# 检查文件${USB_PATH}/script_bootloader/user_scripts/swap/swap_enable.service是否存在
+if [ -e "${USB_PATH}/script_bootloader/user_scripts/swap/swap_enable.service" ]
+then
+    # Load ${USB_PATH}/script_bootloader/user_scripts/swap/swap_enable.service
+    # 如果文件${USB_PATH}/script_bootloader/user_scripts/swap/swap_enable.service存在，则执行
+    ${USB_PATH}/script_bootloader/user_scripts/swap/swap_enable.service
 fi
 #
 ########## END ##########
@@ -103,33 +126,33 @@ fi
 #
 # 对于部分华硕官方固件，/opt目录中存在目录scripts，需将其复制到U盘中
 # 检查目录/opt/scripts/是否存在
-# 检查目录/tmp/mnt/ASUS_ROUTER/scripts/是否存在
+# 检查目录${USB_PATH}/scripts/是否存在
 # 为防止日后梅林固件亦如此，故此段代码不并入下一段
-if [ -d '/opt/scripts/' ] && [ ! -d '/tmp/mnt/ASUS_ROUTER/scripts/' ]
+if [ -d "/opt/scripts/" ] && [ ! -d "${USB_PATH}/scripts/" ]
 then
-    # Copy /opt/scripts/ to /tmp/mnt/ASUS_ROUTER/
-    # 如果目录/opt/scripts/存在，且目录/tmp/mnt/ASUS_ROUTER/scripts/不存在，则执行
-    cp -R /opt/scripts/ /tmp/mnt/ASUS_ROUTER/
+    # Copy /opt/scripts/ to ${USB_PATH}/
+    # 如果目录/opt/scripts/存在，且目录${USB_PATH}/scripts/不存在，则执行
+    cp -R /opt/scripts/ ${USB_PATH}/
     logger -st "($(basename $0))" $$ "***** FOLDER SCRIPTS HAS BEEN COPIED *****"
 fi
 #
 # Take the appropriate way to make /opt available according to the type of firmware
 # 根据固件类型，采用适当方法使目录/opt可用
-if [ $ROUTER_TYPE == 'ASUS_MERLIN' ]
+if [ ${ROUTER_TYPE} == "ASUS_MERLIN" ]
 then
     # If it is ASUS_MERLIN, then create soft link file /tmp/opt
     # 如果是梅林固件，则创建软链接文件/tmp/opt
-    ln -sf /tmp/mnt/ASUS_ROUTER /tmp/opt
+    ln -sf ${USB_PATH} /tmp/opt
     #
 else
     # If it is ASUSWRT, then mount the USB flash drive to /opt
     # 如果是华硕官方固件，则挂载U盘至目录/opt
-    mount $DEV_NAME /opt
+    mount ${DEV_NAME} /opt
 fi
 #
 # Check if /opt/etc/init.d/rc.unslung exists
 # 检查文件/opt/etc/init.d/rc.unslung是否存在
-if [ -e '/opt/etc/init.d/rc.unslung' ]
+if [ -e "/opt/etc/init.d/rc.unslung" ]
 then
     # Start /opt/etc/init.d/rc.unslung
     # 如果文件/opt/etc/init.d/rc.unslung存在，则执行
@@ -137,31 +160,30 @@ then
     logger -st "($(basename $0))" $$ "***** ENTWARE HAS BEEN ENABLED *****"
     #
 else
-    # Stop and Exit
-    # 如果文件/opt/etc/init.d/rc.unslung不存在，则该脚本终止
+    # Do nothing but prompt the user
+    # 如果文件/opt/etc/init.d/rc.unslung不存在，则执行
     logger -st "($(basename $0))" $$ "***** ENTWARE CAN NOT BE ENABLED *****"
-    logger -st "($(basename $0))" $$ "***** EXIT *****"
-    exit 3
 fi
 #
 ########## END ##########
 #
 #
-########## MOUNT HOME ##########
+########## LOCATE AND LOAD THE LIST OF USER'S CUSTOM SCRIPTS ##########
 #
-# Check if /tmp/mnt/ASUS_ROUTER/home/root/ exists
-# 检查目录/tmp/mnt/ASUS_ROUTER/home/root/是否存在
-if [ -d '/tmp/mnt/ASUS_ROUTER/home/root/' ]
+# Check if ${USB_PATH}/script_bootloader/user_scripts/list_of_user_custom_scripts exists
+# 检查用户自定义脚本列表（本例中，该脚本为${USB_PATH}/script_bootloader/user_scripts/list_of_user_custom_scripts）是否存在
+if [ -e "${USB_PATH}/script_bootloader/user_scripts/list_of_user_custom_scripts" ]
 then
-    # Mount /tmp/mnt/ASUS_ROUTER/home/ to /tmp/home/
-    # 如果目录/tmp/mnt/ASUS_ROUTER/home/root/存在，则执行
-    mount /tmp/mnt/ASUS_ROUTER/home/ /tmp/home/
-    logger -st "($(basename $0))" $$ "***** HOME HAS BEEN MOUNTED *****"
+    logger -st "($(basename $0))" $$ "***** LIST OF USER'S CUSTOM SCRIPTS EXISTS *****"
+    # Load user's custom scripts
+    # 如果用户自定义脚本列表存在，则执行该脚本
+    logger -st "($(basename $0))" $$ "***** LOAD THE LIST OF USER'S CUSTOM SCRIPTS *****"
+    ${USB_PATH}/script_bootloader/user_scripts/list_of_user_custom_scripts
     #
 else
     # Do nothing but prompt the user
-    # 如果目录/tmp/mnt/ASUS_ROUTER/home/root/不存在，则执行ssss
-    logger -st "($(basename $0))" $$ "***** HOME HAS NOT BEEN MOUNTED *****"
+    # 如果用户自定义脚本列表不存在，则执行
+    logger -st "($(basename $0))" $$ "***** UNABLE TO LOCATE THE LIST OF USER'S CUSTOM SCRIPTS *****"
 fi
 #
 ########## END ##########
