Release Version 15.0&15.1

diff --git a/script_bootloader/usr/debian/bin/debian_install b/script_bootloader/usr/debian/bin/debian_install
--- a/script_bootloader/usr/debian/bin/debian_install
+++ b/script_bootloader/usr/debian/bin/debian_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,35 +14,43 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # ENTWARE_BIN: The directory which contains all the common executable files installed by Entware
 # 设置自定义变量ENTWARE_BIN为Entware安装的普通可执行文件目录
-ENTWARE_BIN=${USB_MOUNT_POINT}/bin
+ENTWARE_BIN="${USB_MOUNT_POINT}/bin"
 #
 # ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
 # 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
+#
+# ENTWARE_MONITD: The directory which contains all the configuration files used by monit
+# 设置自定义变量ENTWARE_MONITD为monit配置文件目录
+ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/debian
+PRIVATE_ROOT="${SBL_SYS_USR}/debian"
+#
+# PRIVATE_BIN: The directory which contains all the executable files related to this program
+# 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
+PRIVATE_BIN="${PRIVATE_ROOT}/bin"
 #
 # PRIVATE_ETC: The directory which contains all the configuration files related to this program
 # 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
+PRIVATE_ETC="${PRIVATE_ROOT}/etc"
 #
 # PRIVATE_USR: The directory which contains all the external software resources related to this program
 # 设置自定义变量PRIVATE_USR为此程序外部软件资源目录
-PRIVATE_USR=${PRIVATE_ROOT}/usr
+PRIVATE_USR="${PRIVATE_ROOT}/usr"
 #
 # ROUTER_ARCHITECTURE: Architecture of the ASUS Router
 # 设置自定义变量ROUTER_ARCHITECTURE为华硕路由器架构
-case $(/opt/bin/uname -m) in
+case "$(/opt/bin/uname -m)" in
     "aarch64")
         ROUTER_ARCHITECTURE="arm64"
         ;;
@@ -56,16 +64,14 @@ case $(/opt/bin/uname -m) in
         ;;
     "mips")
         ROUTER_ARCHITECTURE="mipsel"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${ROUTER_ARCHITECTURE} IS NOT SUPPORTED TEMPORARILY"
         #
-        # Prompt the user that Debian doesn't support ${ROUTER_ARCHITECTURE}
-        # 提示用户Debian不支持${ROUTER_ARCHITECTURE}
-        /opt/bin/echo "($(basename $0)): $$ ***** DEBIAN DOESN'T SUPPORT ${ROUTER_ARCHITECTURE} *****"
         exit 6
         ;;
     *)
         # Do nothing but prompt the user
         # 如果路由器架构不符合上述三种情况，则执行
-        /opt/bin/echo "($(basename $0)): $$ ***** ROUTER ARCHITECTURE IS UNKNOWN *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ROUTER ARCHITECTURE IS UNKNOWN"
         #
         exit 3
         ;;
@@ -73,7 +79,7 @@ esac
 #
 # DEBIAN_VERSION: Version of Debian
 # 设置自定义变量DEBIAN_VERSION为Debian版本
-case $(/opt/bin/uname -r | /opt/bin/sed -E -n -e 's/^([[:digit:]]).*/\1/p') in
+case "$(/opt/bin/uname -r | /opt/bin/sed -E -n -e 's/^([[:digit:]]).*/\1/p')" in
     "2")
         DEBIAN_VERSION="jessie"
         ;;
@@ -83,7 +89,7 @@ case $(/opt/bin/uname -r | /opt/bin/sed -E -n -e 's/^([[:digit:]]).*/\1/p') in
     *)
         # Do nothing but prompt the user
         # 如果路由器架构不符合上述三种情况，则执行
-        /opt/bin/echo "($(basename $0)): $$ ***** VERSION OF KERNEL IS UNKNOWN *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: KERNEL VERSION IS UNKNOWN"
         #
         exit 7
         ;;
@@ -99,14 +105,14 @@ SERVICE_NAME="DEBIAN"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-/opt/bin/echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -115,36 +121,57 @@ SERVICE_FUNCTION="INSTALLATION"
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
-    # Download Debian
-    # 下载Debian
-    /opt/bin/mkdir -p ${PRIVATE_USR}
-    /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P ${PRIVATE_USR} ${DOWNLOAD_LINK}
-    #
-    # Prepare Debian Environment
-    # 准备Debian环境
-    /opt/bin/tar -xzvf ${PRIVATE_USR}/debian-${DEBIAN_VERSION}-${ROUTER_ARCHITECTURE}.tar.gz -C ${USB_MOUNT_POINT}/
-    /opt/bin/mkdir -p ${USB_MOUNT_POINT}/debian_mnt/
-    /opt/bin/cp ${PRIVATE_ETC}/S99debian ${ENTWARE_ETC}/init.d/
-    /opt/bin/chmod 755 ${ENTWARE_ETC}/init.d/S99debian
-    /opt/bin/cp ${PRIVATE_ETC}/chroot-services.list ${ENTWARE_ETC}/
-    /opt/bin/chmod 755 ${ENTWARE_ETC}/chroot-services.list
-    /opt/bin/cp -s ${ENTWARE_ETC}/init.d/S99debian ${ENTWARE_BIN}/debian
-    /opt/bin/cp /etc/hosts ${USB_MOUNT_POINT}/debian/etc/
-    #
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
-    #
-    exit 0
+    # Check if MONIT MANAGEMENT SYSTEM has been deployed
+    # 检查MONIT MANAGEMENT SYSTEM是否已部署
+    if [ -e "/opt/bin/monit" ]
+    then
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED"
+        #
+        # Download Debian
+        # 下载Debian
+        /opt/bin/mkdir -p "${PRIVATE_USR}"
+        /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_USR}" "${DOWNLOAD_LINK}"
+        #
+        # Prepare Debian Environment
+        # 准备Debian环境
+        /opt/bin/tar -xzvf "${PRIVATE_USR}/debian-${DEBIAN_VERSION}-${ROUTER_ARCHITECTURE}.tar.gz" -C "/opt"
+        /opt/bin/mkdir -p "/opt/debian_mnt"
+        /opt/bin/touch "/opt/etc/chroot-services.list"
+        /opt/bin/chmod 755 "/opt/etc/chroot-services.list"
+        /opt/bin/cp -f "/etc/hosts" "/opt/debian/etc"
+        /opt/bin/cp -fs "${PRIVATE_BIN}/debian" "${ENTWARE_BIN}/debian"
+        #
+        # Configure monit
+        # 配置monit
+        /opt/bin/cp -f "${PRIVATE_ETC}/monit.d/debian" "${ENTWARE_MONITD}"
+        /opt/bin/chmod 600 "${ENTWARE_MONITD}/debian"
+        /opt/bin/mv -f "${ENTWARE_MONITD}/debian" "${ENTWARE_MONITD}/debian.on"
+        /opt/bin/monit reload
+        #
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 0
+        #
+    else
+        # Do nothing but prompt the user
+        # 如果MONIT MANAGEMENT SYSTEM未部署，则执行
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 2
+    fi
     #
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** PLEASE ENABLE ENTWARE FIRST *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     exit 1
 fi
diff --git a/script_bootloader/usr/debian/bin/debian_uninstall b/script_bootloader/usr/debian/bin/debian_uninstall
--- a/script_bootloader/usr/debian/bin/debian_uninstall
+++ b/script_bootloader/usr/debian/bin/debian_uninstall
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,15 +14,19 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # ENTWARE_BIN: The directory which contains all the common executable files installed by Entware
 # 设置自定义变量ENTWARE_BIN为Entware安装的普通可执行文件目录
-ENTWARE_BIN=${USB_MOUNT_POINT}/bin
+ENTWARE_BIN="${USB_MOUNT_POINT}/bin"
 #
 # ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
 # 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
+#
+# ENTWARE_MONITD: The directory which contains all the configuration files used by monit
+# 设置自定义变量ENTWARE_MONITD为monit配置文件目录
+ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -30,14 +34,14 @@ SERVICE_NAME="DEBIAN"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="UNINSTALLATION"
+SERVICE_FUNCTION="UNINSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-logger -st "($(basename $0))" $$ "*--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -46,26 +50,56 @@ logger -st "($(basename $0))" $$ "*--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} 
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    logger -st "($(basename $0))" $$ "***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
-    # Destroy Debian Environment
-    # 销毁Debian环境
-    /opt/bin/rm -rf ${USB_MOUNT_POINT}/debian/
-    /opt/bin/rm -rf ${USB_MOUNT_POINT}/debian_mnt/
-    /opt/bin/rm -f ${ENTWARE_ETC}/init.d/S99debian
-    /opt/bin/rm -f ${ENTWARE_ETC}/chroot-services.list
-    /opt/bin/rm -f ${ENTWARE_BIN}/debian
-    #
-    logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+    # Check if MONIT MANAGEMENT SYSTEM has been deployed
+    # 检查MONIT MANAGEMENT SYSTEM是否已部署
+    if [ -e "/opt/bin/monit" ]
+    then
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED"
+        #
+        # Stop monit service
+        # 停止monit服务
+        /opt/bin/monit stop "DEBIAN" > /dev/null 2>&1
+        /opt/bin/sleep 30
+        #
+        # Destroy Debian Environment
+        # 销毁Debian环境
+        /opt/bin/rm -rf "/opt/debian"
+        /opt/bin/rm -rf "/opt/debian_mnt"
+        /opt/bin/rm -f "/opt/etc/chroot-services.list"
+        /opt/bin/rm -f "${ENTWARE_BIN}/debian"
+        #
+        # Configure monit
+        # 配置monit
+        /opt/bin/rm -f "${ENTWARE_MONITD}/debian"
+        /opt/bin/rm -f "${ENTWARE_MONITD}/debian.on"
+        /opt/bin/monit reload
+        #
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 0
+        #
+    else
+        # Do nothing but prompt the user
+        # 如果MONIT MANAGEMENT SYSTEM未部署，则执行
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 2
+    fi
     #
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    logger -st "($(basename $0))" $$ "***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    logger -st "($(basename $0))" $$ "***** PLEASE ENABLE ENTWARE FIRST *****"
-    logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+    #
+    exit 1
 fi
 #
 ########## END ##########
diff --git a/script_bootloader/usr/filebrowser/bin/filebrowser_install b/script_bootloader/usr/filebrowser/bin/filebrowser_install
--- a/script_bootloader/usr/filebrowser/bin/filebrowser_install
+++ b/script_bootloader/usr/filebrowser/bin/filebrowser_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,64 +14,67 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
 # 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
 #
 # ENTWARE_MONITD: The directory which contains all the configuration files used by monit
 # 设置自定义变量ENTWARE_MONITD为monit配置文件目录
-ENTWARE_MONITD=${ENTWARE_ETC}/monit.d
+ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 #
 # ENTWARE_FWD: The directory which contains all the configuration files used by fwd
 # 设置自定义变量ENTWARE_FWD为fwd配置文件目录
-ENTWARE_FWD=${ENTWARE_ETC}/fw.d
+ENTWARE_FWD="${ENTWARE_ETC}/fw.d"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/filebrowser
+PRIVATE_ROOT="${SBL_SYS_USR}/filebrowser"
 #
 # PRIVATE_BIN: The directory which contains all the executable files related to this program
 # 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
-PRIVATE_BIN=${PRIVATE_ROOT}/bin
+PRIVATE_BIN="${PRIVATE_ROOT}/bin"
 #
 # PRIVATE_ETC: The directory which contains all the configuration files related to this program
 # 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
+PRIVATE_ETC="${PRIVATE_ROOT}/etc"
 #
 # PRIVATE_USR: The directory which contains all the external software resources related to this program
 # 设置自定义变量PRIVATE_USR为此程序外部软件资源目录
-PRIVATE_USR=${PRIVATE_ROOT}/usr
+PRIVATE_USR="${PRIVATE_ROOT}/usr"
 #
 # LATEST_VERSION: Version of the latest filebrowser
 # 设置自定义变量LATEST_VERSION为最新版filebrowser的版本号
-LATEST_VERSION=$(/opt/bin/curl -s https://api.github.com/repos/filebrowser/filebrowser/releases/latest | /opt/bin/sed -E -n -e 's/^[[:space:]]*\"tag_name\":[[:space:]]*\"(.*)\".*/\1/p' 2> /dev/null)
+LATEST_VERSION="$(/opt/bin/curl -s "https://api.github.com/repos/filebrowser/filebrowser/releases/latest" | /opt/bin/sed -E -n -e 's/^[[:space:]]*\"tag_name\":[[:space:]]*\"(.*)\".*/\1/p')"
 #
 # OPERATING_SYSTEM: Operating system of the ASUS Router
 # 设置自定义变量OPERATING_SYSTEM为华硕路由器系统
-OPERATING_SYSTEM=$(/opt/bin/uname | /opt/bin/sed 's/L/l/g')
+OPERATING_SYSTEM="$(/opt/bin/uname | /opt/bin/sed -E 's/[[:upper:]]/\l&/g')"
 #
 # ROUTER_ARCHITECTURE: Architecture of the ASUS Router
 # 设置自定义变量ROUTER_ARCHITECTURE为华硕路由器架构
-case $(/opt/bin/uname -m) in
+case "$(/opt/bin/uname -m)" in
     "aarch64")
         ROUTER_ARCHITECTURE="arm64"
         ;;
     "armv7l")
         ROUTER_ARCHITECTURE="armv5"
         ;;
-    #"mips")
-    #    ROUTER_ARCHITECTURE="mipsle"
-    #    ;;
+    "mips")
+        ROUTER_ARCHITECTURE="mipsle"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${ROUTER_ARCHITECTURE} IS NOT SUPPORTED TEMPORARILY"
+        #
+        exit 6
+        ;;
     *)
         # Do nothing but prompt the user
         # 如果路由器架构不符合上述三种情况，则执行
-        /opt/bin/echo "($(basename $0)): $$ ***** ROUTER ARCHITECTURE IS UNKNOWN *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ROUTER ARCHITECTURE IS UNKNOWN"
         #
         exit 3
         ;;
@@ -83,11 +86,11 @@ DOWNLOAD_LINK="https://github.com/filebrowser/filebrowser/releases/download/${LA
 #
 # ADMINUSER: The administrator of the router
 # 设置环境变量ADMINUSER为路由器管理页面的登陆帐号
-ADMINUSER=$(nvram get http_username)
+ADMINUSER="$(nvram get http_username)"
 #
 # ADMINPASSWORD: The administrator's password of the router
 # 设置环境变量ADMINPASSWORD为路由器管理页面的登陆密码
-ADMINPASSWORD=$(nvram get http_passwd)
+ADMINPASSWORD="$(nvram get http_passwd)"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -95,14 +98,14 @@ SERVICE_NAME="FILE-BROWSER"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-/opt/bin/echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -111,70 +114,70 @@ SERVICE_FUNCTION="INSTALLATION"
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
     # Check if MONIT MANAGEMENT SYSTEM has been deployed
     # 检查MONIT MANAGEMENT SYSTEM是否已部署
     if [ -e "/opt/bin/monit" ]
     then
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED"
         #
         # Remove vestigial filebrowser package
         # 删除遗留的filebrowser包
-        /opt/bin/rm -f ${PRIVATE_BIN}/${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-filebrowser.tar.gz > /dev/null 2>&1
+        /opt/bin/rm -f "${PRIVATE_BIN}/${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-filebrowser.tar.gz"
         #
         # Download filebrowser package
         # 下载filebrowser包
-        /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P ${PRIVATE_BIN} ${DOWNLOAD_LINK}
+        /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
         #
         # Create directory ${PRIVATE_USR}
         # 创建${PRIVATE_USR}目录
-        /opt/bin/mkdir ${PRIVATE_USR}
+        /opt/bin/mkdir "${PRIVATE_USR}"
         #
         # Unzip filebrowser package
         # 解压filebrowser包
-        /opt/bin/tar -xzvf ${PRIVATE_BIN}/${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-filebrowser.tar.gz -C ${PRIVATE_USR}/
+        /opt/bin/tar -xzvf "${PRIVATE_BIN}/${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-filebrowser.tar.gz" -C "${PRIVATE_USR}"
         #
         # Remove filebrowser package
         # 删除filebrowser包
-        /opt/bin/rm -f ${PRIVATE_BIN}/${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-filebrowser.tar.gz > /dev/null 2>&1
+        /opt/bin/rm -f "${PRIVATE_BIN}/${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-filebrowser.tar.gz"
         #
         # Configure filebrowser
         # 配置filebrowser
-        ${PRIVATE_USR}/filebrowser --database "${PRIVATE_ETC}/database.db" config init --address "0.0.0.0" --branding.disableExternal --locale "zh-cn" --perm.admin --port "35248" --scope "/root/" --sorting.asc --sorting.by "name" --viewMode "list"
+        "${PRIVATE_USR}/filebrowser" --database "${PRIVATE_ETC}/database.db" config init --address "0.0.0.0" --branding.disableExternal --locale "zh-cn" --perm.admin --port "35248" --scope "/root" --sorting.asc --sorting.by "name" --viewMode "list"
         #
-        ${PRIVATE_USR}/filebrowser --database "${PRIVATE_ETC}/database.db" users add "${ADMINUSER}" "${ADMINPASSWORD}"
+        "${PRIVATE_USR}/filebrowser" --database "${PRIVATE_ETC}/database.db" users add "${ADMINUSER}" "${ADMINPASSWORD}"
         #
-        ${PRIVATE_USR}/filebrowser --database "${PRIVATE_ETC}/database.db" config export "${PRIVATE_ETC}/config.json"
+        "${PRIVATE_USR}/filebrowser" --database "${PRIVATE_ETC}/database.db" config export "${PRIVATE_ETC}/config.json"
         #
         # Configure fwd
         # 配置fwd
-        /opt/bin/cp ${PRIVATE_ETC}/fw.d/filebrowser_open ${ENTWARE_FWD}/
+        /opt/bin/cp -f "${PRIVATE_ETC}/fw.d/filebrowser_open" "${ENTWARE_FWD}"
         #
         # Configure monit
         # 配置monit
-        /opt/bin/cp ${PRIVATE_ETC}/monit.d/filebrowser ${ENTWARE_MONITD}/
-        /opt/bin/chmod 600 ${ENTWARE_MONITD}/filebrowser
-        /opt/bin/mv ${ENTWARE_MONITD}/filebrowser ${ENTWARE_MONITD}/filebrowser.on
+        /opt/bin/cp -f "${PRIVATE_ETC}/monit.d/filebrowser" "${ENTWARE_MONITD}"
+        /opt/bin/chmod 600 "${ENTWARE_MONITD}/filebrowser"
+        /opt/bin/mv -f "${ENTWARE_MONITD}/filebrowser" "${ENTWARE_MONITD}/filebrowser.on"
         #
-        /opt/bin/cp ${PRIVATE_ETC}/monit.d/fw_filter_INPUT_filebrowser ${ENTWARE_MONITD}/
-        /opt/bin/chmod 600 ${ENTWARE_MONITD}/fw_filter_INPUT_filebrowser
-        /opt/bin/mv ${ENTWARE_MONITD}/fw_filter_INPUT_filebrowser ${ENTWARE_MONITD}/fw_filter_INPUT_filebrowser.on
+        /opt/bin/cp -f "${PRIVATE_ETC}/monit.d/fw_filter_INPUT_filebrowser" "${ENTWARE_MONITD}"
+        /opt/bin/chmod 600 "${ENTWARE_MONITD}/fw_filter_INPUT_filebrowser"
+        /opt/bin/mv -f "${ENTWARE_MONITD}/fw_filter_INPUT_filebrowser" "${ENTWARE_MONITD}/fw_filter_INPUT_filebrowser.on"
         #
         /opt/bin/monit reload
         #
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
         #
         exit 0
         #
     else
         # Do nothing but prompt the user
         # 如果MONIT MANAGEMENT SYSTEM未部署，则执行
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
         #
         exit 2
     fi
@@ -182,9 +185,9 @@ then
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** PLEASE ENABLE ENTWARE FIRST *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     exit 1
 fi
diff --git a/script_bootloader/usr/mailx/bin/mailx_install b/script_bootloader/usr/mailx/bin/mailx_install
--- a/script_bootloader/usr/mailx/bin/mailx_install
+++ b/script_bootloader/usr/mailx/bin/mailx_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,35 +14,19 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
-#
-# ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
-# 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/mailx
+PRIVATE_ROOT="${SBL_SYS_USR}/he_ddns"
 #
-# PRIVATE_ETC: The directory which contains all the configuration files related to this program
-# 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
-#
-# SMTP_SERVER: The SMTP server
-# 设置自定义变量SMTP_SERVER为SMTP服务器地址
-SMTP_SERVER=''
-#
-# SENDER: The sender of the mail
-# 设置自定义变量SENDER为发件人
-SENDER=''
-#
-# PASSWORD: The password of sender
-# 设置自定义变量PASSWORD为发件人密码
-PASSWORD=''
+# PRIVATE_BIN: The directory which contains all the executable files related to this program
+# 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
+PRIVATE_BIN="${PRIVATE_ROOT}/bin"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -50,14 +34,14 @@ SERVICE_NAME="MAILX"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-/opt/bin/echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -66,9 +50,9 @@ SERVICE_FUNCTION="INSTALLATION"
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
     # Update the list of available packages
     # 更新可用程序包列表
@@ -80,26 +64,35 @@ then
     #
     # Configure nail
     # 配置nail
-    /opt/bin/mkdir ${PRIVATE_ETC}
-    /opt/bin/cp ${ENTWARE_ETC}/nail.rc ${PRIVATE_ETC}/nail.rc.bak
-    /opt/bin/sed -i '/^set from=.*/s/^/#/' ${ENTWARE_ETC}/nail.rc
-    /opt/bin/sed -i '/^set set smtp.*/s/^/#/' ${ENTWARE_ETC}/nail.rc
-    /opt/bin/echo "set from=${SENDER}" >> ${ENTWARE_ETC}/nail.rc
-    /opt/bin/echo "set smtp=${SMTP_SERVER}" >> ${ENTWARE_ETC}/nail.rc
-    /opt/bin/echo "set smtp-auth-user=${SENDER}" >> ${ENTWARE_ETC}/nail.rc
-    /opt/bin/echo "set smtp-auth-password=${PASSWORD}" >> ${ENTWARE_ETC}/nail.rc
-    /opt/bin/echo "set smtp-auth=login" >> ${ENTWARE_ETC}/nail.rc
+    /opt/bin/cp -f "/opt/etc/nail.rc" "/opt/etc/nail.rc.bak"
+    /opt/bin/sed -i '/^set from=.*/s/^/#/' "/opt/etc/nail.rc"
+    /opt/bin/sed -i '/^set smtp.*/s/^/#/' "/opt/etc/nail.rc"
+    /opt/bin/echo -e "set from=" >> "/opt/etc/nail.rc"
+    /opt/bin/echo -e "set smtp=" >> "/opt/etc/nail.rc"
+    /opt/bin/echo -e "set smtp-auth-user=" >> "/opt/etc/nail.rc"
+    /opt/bin/echo -e "set smtp-auth-password=" >> "/opt/etc/nail.rc"
+    /opt/bin/echo -e "set smtp-auth=" >> "/opt/etc/nail.rc"
     #
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+    "${PRIVATE_BIN}/mailx_configure"
     #
-    exit 0
+    if [ ${?} -eq 0 ]
+    then
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 0
+        #
+    else
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 2
+    fi
     #
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** PLEASE ENABLE ENTWARE FIRST *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     exit 1
 fi
diff --git a/script_bootloader/usr/ntpd/bin/ntpd_install b/script_bootloader/usr/ntpd/bin/ntpd_install
--- a/script_bootloader/usr/ntpd/bin/ntpd_install
+++ b/script_bootloader/usr/ntpd/bin/ntpd_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,27 +14,31 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
 # 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
 #
 # ENTWARE_MONITD: The directory which contains all the configuration files used by monit
 # 设置自定义变量ENTWARE_MONITD为monit配置文件目录
-ENTWARE_MONITD=${ENTWARE_ETC}/monit.d
+ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/ntpd
+PRIVATE_ROOT="${SBL_SYS_USR}/ntpd"
+#
+# PRIVATE_BIN: The directory which contains all the executable files related to this program
+# 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
+PRIVATE_BIN="${PRIVATE_ROOT}/bin"
 #
 # PRIVATE_ETC: The directory which contains all the configuration files related to this program
 # 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
+PRIVATE_ETC="${PRIVATE_ROOT}/etc"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -42,14 +46,14 @@ SERVICE_NAME="NTPD"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-/opt/bin/echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -58,15 +62,15 @@ SERVICE_FUNCTION="INSTALLATION"
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
     # Check if MONIT MANAGEMENT SYSTEM has been deployed
     # 检查MONIT MANAGEMENT SYSTEM是否已部署
     if [ -e "/opt/bin/monit" ]
     then
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED"
         #
         # Update the list of available packages
         # 更新可用程序包列表
@@ -76,34 +80,40 @@ then
         # 安装ntpd
         /opt/bin/opkg install ntpd
         #
-        # Disable ${ENTWARE_ETC}/init.d/S77ntpd
-        # 禁用${ENTWARE_ETC}/init.d/S77ntpd
-        /opt/bin/cp ${ENTWARE_ETC}/init.d/S77ntpd ${PRIVATE_ETC}/S77ntpd.bak
-        /opt/bin/sed -i '/^ENABLED.*/s/^/#/' ${ENTWARE_ETC}/init.d/S77ntpd
-        /opt/bin/sed -i '/^#ENABLED.*/a\ENABLED=no' ${ENTWARE_ETC}/init.d/S77ntpd
+        # Disable /opt/etc/init.d/S*ntpd
+        # 禁用/opt/etc/init.d/S*ntpd
+        /opt/bin/sed -i '/^ENABLED.*/s/^/#/' /opt/etc/init.d/S*ntpd
+        /opt/bin/sed -i '/^#ENABLED.*/a\ENABLED=no' /opt/etc/init.d/S*ntpd
         #
         # Configure ntpd
         # 配置ntpd
-        /opt/bin/mv ${ENTWARE_ETC}/ntp.conf ${PRIVATE_ETC}/ntp.conf.bak
-        /opt/bin/chmod 600 ${PRIVATE_ETC}/ntp.conf
+        "${PRIVATE_BIN}/ntpd_configure"
         #
-        # Configure monit
-        # 配置monit
-        /opt/bin/cp ${PRIVATE_ETC}/monit.d/ntpd ${ENTWARE_MONITD}/
-        /opt/bin/chmod 600 ${ENTWARE_MONITD}/ntpd
-        /opt/bin/mv ${ENTWARE_MONITD}/ntpd ${ENTWARE_MONITD}/ntpd.on
-        /opt/bin/monit reload
-        #
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
-        #
-        exit 0
+        if [ ${?} -eq 0 ]
+        then
+            # Configure monit
+            # 配置monit
+            /opt/bin/cp -f "${PRIVATE_ETC}/monit.d/ntpd" "${ENTWARE_MONITD}"
+            /opt/bin/chmod 600 "${ENTWARE_MONITD}/ntpd"
+            /opt/bin/mv -f "${ENTWARE_MONITD}/ntpd" "${ENTWARE_MONITD}/ntpd.on"
+            /opt/bin/monit reload
+            #
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            exit 0
+            #
+        else
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            exit 3
+        fi
         #
     else
         # Do nothing but prompt the user
         # 如果MONIT MANAGEMENT SYSTEM未部署，则执行
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
         #
         exit 2
     fi
@@ -111,9 +121,9 @@ then
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** PLEASE ENABLE ENTWARE FIRST *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     exit 1
 fi
diff --git a/script_bootloader/usr/samba/bin/samba_install b/script_bootloader/usr/samba/bin/samba_install
--- a/script_bootloader/usr/samba/bin/samba_install
+++ b/script_bootloader/usr/samba/bin/samba_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,45 +14,35 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
 # 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
 #
 # ENTWARE_MONITD: The directory which contains all the configuration files used by monit
 # 设置自定义变量ENTWARE_MONITD为monit配置文件目录
-ENTWARE_MONITD=${ENTWARE_ETC}/monit.d
+ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/samba
+PRIVATE_ROOT="${SBL_SYS_USR}/samba"
 #
 # PRIVATE_ETC: The directory which contains all the configuration files related to this program
 # 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
-#
-# COMPUTER_NAME: The computer_name defined in nvram
-# 设置自定义变量COMPUTER_NAME为nvram中定义的computer_name
-COMPUTER_NAME="$(nvram get computer_name 2> /dev/null)"
-if [ -z "${COMPUTER_NAME}" ]
-then
-    COMPUTER_NAME="${ROUTER_MODEL}"
-    nvram set computer_name="${COMPUTER_NAME}"
-    nvram commit
-fi
+PRIVATE_ETC="${PRIVATE_ROOT}/etc"
 #
 # ADMINUSER: The administrator of the router
 # 设置环境变量ADMINUSER为路由器管理页面的登陆帐号
-ADMINUSER=$(nvram get http_username)
+ADMINUSER="$(nvram get http_username)"
 #
 # ADMINPASSWORD: The administrator's password of the router
 # 设置环境变量ADMINPASSWORD为路由器管理页面的登陆密码
-ADMINPASSWORD=$(nvram get http_passwd)
+ADMINPASSWORD="$(nvram get http_passwd)"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -60,14 +50,14 @@ SERVICE_NAME="SAMBA"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-/opt/bin/echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -76,15 +66,15 @@ SERVICE_FUNCTION="INSTALLATION"
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
     # Check if MONIT MANAGEMENT SYSTEM has been deployed
     # 检查MONIT MANAGEMENT SYSTEM是否已部署
     if [ -e "/opt/bin/monit" ]
     then
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED"
         #
         # Update the list of available packages
         # 更新可用程序包列表
@@ -104,50 +94,49 @@ then
         #
         # Configure dbus-daemon
         # 配置dbus-daemon
-        /opt/bin/mv /opt/etc/dbus-1/system.d/avahi-dbus.conf /opt/etc/dbus-1/system.d/avahi-dbus.conf.bak
-        /opt/bin/sed -i "s/root/${ADMINUSER}/g" ${PRIVATE_ETC}/dbus/avahi-dbus.conf
-        /opt/bin/cp ${PRIVATE_ETC}/dbus/avahi-dbus.conf /opt/etc/dbus-1/system.d/
-        /opt/bin/chmod 644 /opt/etc/dbus-1/system.d/avahi-dbus.conf
+        /opt/bin/mv -f "/opt/etc/dbus-1/system.d/avahi-dbus.conf" "/opt/etc/dbus-1/system.d/avahi-dbus.conf.bak"
+        /opt/bin/cp -f "${PRIVATE_ETC}/dbus/avahi-dbus.conf.template" "${PRIVATE_ETC}/dbus/avahi-dbus.conf"
+        /opt/bin/sed -i 's/ADMINUSER/'"${ADMINUSER}"'/g' "${PRIVATE_ETC}/dbus/avahi-dbus.conf"
+        /opt/bin/cp -f "${PRIVATE_ETC}/dbus/avahi-dbus.conf" "/opt/etc/dbus-1/system.d"
+        /opt/bin/chmod 644 "/opt/etc/dbus-1/system.d/avahi-dbus.conf"
         #
-        /opt/bin/mv /opt/share/dbus-1/system.conf /opt/share/dbus-1/system.conf.bak
-        /opt/bin/sed -i "s/root/${ADMINUSER}/g" ${PRIVATE_ETC}/dbus/system.conf
-        /opt/bin/cp ${PRIVATE_ETC}/dbus/system.conf /opt/share/dbus-1/
-        /opt/bin/chmod 644 /opt/share/dbus-1/system.conf
+        /opt/bin/mv -f "/opt/share/dbus-1/system.conf" "/opt/share/dbus-1/system.conf.bak"
+        /opt/bin/cp -f "${PRIVATE_ETC}/dbus/system.conf.template" "${PRIVATE_ETC}/dbus/system.conf"
+        /opt/bin/sed -i 's/ADMINUSER/'"${ADMINUSER}"'/g' "${PRIVATE_ETC}/dbus/system.conf"
+        /opt/bin/cp -f "${PRIVATE_ETC}/dbus/system.conf" "/opt/share/dbus-1"
+        /opt/bin/chmod 644 "/opt/share/dbus-1/system.conf"
         #
         # Disable /opt/etc/init.d/S91smb
         # 禁用/opt/etc/init.d/S91smb
-        /opt/bin/mv /opt/etc/init.d/S91smb ${PRIVATE_ETC}/S91smb.bak
+        /opt/bin/mv -f /opt/etc/init.d/S*smb "${PRIVATE_ETC}"
         #
         # Configure samba
         # 配置samba
-        /opt/bin/cp /opt/etc/samba/smb.conf /opt/etc/samba/smb.conf.bak
-        /opt/bin/sed -i '/netbios name/s/^/#/' /opt/etc/samba/smb.conf
-        /opt/bin/sed -i "\#netbios name#a\        netbios name = ${COMPUTER_NAME}" /opt/etc/samba/smb.conf
-        /opt/bin/sed -i '/socket options/s/^/#/' /opt/etc/samba/smb.conf
-        /opt/bin/sed -i "\#socket options#a\        socket options = TCP_NODELAY SO_KEEPALIVE IPTOS_LOWDELAY" /opt/etc/samba/smb.conf
-        /opt/bin/sed -i '/passdb backend/s/^/#/' /opt/etc/samba/smb.conf
-        /opt/bin/sed -i "\#passdb backend#a\        passdb backend = tdbsam:/opt/etc/samba/passdb.tdb" /opt/etc/samba/smb.conf
-        /opt/bin/sed -i '/syslog/s/^/#/' /opt/etc/samba/smb.conf
-        /opt/bin/sed -i '/smb passwd file/s/^/#/' /opt/etc/samba/smb.conf
+        /opt/bin/cp -f "/opt/etc/samba/smb.conf" "/opt/etc/samba/smb.conf.bak"
+        /opt/bin/sed -i '/netbios name/s/^/#/' "/opt/etc/samba/smb.conf"
+        /opt/bin/sed -i '\#netbios name#a\        netbios name = '"${ROUTER_MODEL}"'' "/opt/etc/samba/smb.conf"
+        /opt/bin/sed -i '/socket options/s/^/#/' "/opt/etc/samba/smb.conf"
+        /opt/bin/sed -i '\#socket options#a\        socket options = TCP_NODELAY SO_KEEPALIVE IPTOS_LOWDELAY' "/opt/etc/samba/smb.conf"
+        /opt/bin/sed -i '/passdb backend/s/^/#/' "/opt/etc/samba/smb.conf"
+        /opt/bin/sed -i '\#passdb backend#a\        passdb backend = tdbsam:/opt/etc/samba/passdb.tdb' "/opt/etc/samba/smb.conf"
+        /opt/bin/sed -i '/syslog/s/^/#/' "/opt/etc/samba/smb.conf"
+        /opt/bin/sed -i '/smb passwd file/s/^/#/' "/opt/etc/samba/smb.conf"
         #
-        /opt/bin/sed -i "s/ROUTER/${ROUTER_MODEL}/" ${PRIVATE_ETC}/smb.conf.add
-        /opt/bin/cat ${PRIVATE_ETC}/smb.conf.add >> /opt/etc/samba/smb.conf
+        /opt/bin/cp -f "${PRIVATE_ETC}/smb.conf.add.template" "${PRIVATE_ETC}/smb.conf.add"
+        /opt/bin/sed -i 's/ROUTER_MODEL/'"${ROUTER_MODEL}"'/' "${PRIVATE_ETC}/smb.conf.add"
+        /opt/bin/cat "${PRIVATE_ETC}/smb.conf.add" >> "/opt/etc/samba/smb.conf"
         #
-        /opt/bin/touch /opt/etc/printcap
-        /opt/bin/mkdir -p /opt/var/log/samba
-        /opt/bin/mkdir -p /opt/var/lib/samba/private
-        /opt/bin/mkdir -p /opt/var/cache/samba
-        /opt/bin/mkdir -p /opt/var/run/samba/ncalrpc
-        /opt/bin/chmod 755 /opt/var/lib/samba
-        /opt/bin/chmod 755 /opt/var/cache/samba
-        #
-        # Create default shared directory
-        # 创建默认共享目录
-        #/opt/bin/mkdir /home/root/samba_share
+        /opt/bin/touch "/opt/etc/printcap"
+        /opt/bin/mkdir -p "/opt/var/log/samba"
+        /opt/bin/mkdir -p "/opt/var/lib/samba/private"
+        /opt/bin/mkdir -p "/opt/var/cache/samba"
+        /opt/bin/mkdir -p "/opt/var/run/samba/ncalrpc"
+        /opt/bin/chmod 755 "/opt/var/lib/samba"
+        /opt/bin/chmod 755 "/opt/var/cache/samba"
         #
         # Disable /opt/etc/init.d/S99wsdd2
         # 禁用/opt/etc/init.d/S99wsdd2
-        /opt/bin/mv /opt/etc/init.d/S99wsdd2 ${PRIVATE_ETC}/S99wsdd2.bak
+        /opt/bin/mv -f /opt/etc/init.d/S*wsdd2 "${PRIVATE_ETC}"
         #
         # Create default samba user
         # 创建默认samba用户
@@ -155,27 +144,33 @@ then
         #
         # Configure monit
         # 配置monit
-        /opt/bin/cp ${PRIVATE_ETC}/monit.d/samba_server ${ENTWARE_MONITD}/
-        /opt/bin/chmod 600 ${ENTWARE_MONITD}/samba_server
-        /opt/bin/mv ${ENTWARE_MONITD}/samba_server ${ENTWARE_MONITD}/samba_server.on
+        /opt/bin/cp -f "${PRIVATE_ETC}/monit.d/samba_server" "${ENTWARE_MONITD}"
+        /opt/bin/chmod 600 "${ENTWARE_MONITD}/samba_server"
+        /opt/bin/mv -f "${ENTWARE_MONITD}/samba_server" "${ENTWARE_MONITD}/samba_server.on"
         /opt/bin/monit reload
         #
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 0
         #
     else
         # Do nothing but prompt the user
         # 如果MONIT MANAGEMENT SYSTEM未部署，则执行
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 2
     fi
     #
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** PLEASE ENABLE ENTWARE FIRST *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+    #
+    exit 1
 fi
 #
 ########## END ##########
diff --git a/script_bootloader/usr/samba/bin/samba_uninstall b/script_bootloader/usr/samba/bin/samba_uninstall
--- a/script_bootloader/usr/samba/bin/samba_uninstall
+++ b/script_bootloader/usr/samba/bin/samba_uninstall
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,35 +14,27 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
-#
-# SBL_SYS_ROOT: The root directory for SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
-# 设置自定义变量SBL_SYS_ROOT为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统根目录
-SBL_SYS_ROOT=${USB_MOUNT_POINT}/script_bootloader
-#
-# SBL_SYS_TMP: The directory which contains all the temporary files related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
-# 设置自定义变量SBL_SYS_TMP为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统临时文件目录
-SBL_SYS_TMP=${SBL_SYS_ROOT}/tmp
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${SBL_SYS_ROOT}/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
 # 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
 #
 # ENTWARE_MONITD: The directory which contains all the configuration files used by monit
 # 设置自定义变量ENTWARE_MONITD为monit配置文件目录
-ENTWARE_MONITD=${ENTWARE_ETC}/monit.d
+ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/samba
+PRIVATE_ROOT="${SBL_SYS_USR}/samba"
 #
 # PRIVATE_ETC: The directory which contains all the configuration files related to this program
 # 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
+PRIVATE_ETC="${PRIVATE_ROOT}/etc"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -50,35 +42,81 @@ SERVICE_NAME="SAMBA"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="UNINSTALLATION"
+SERVICE_FUNCTION="UNINSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-logger -st "($(basename $0))" $$ "*--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
 #
-########## INSTALL SAMBA ##########
+########## UNINSTALL SAMBA ##########
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    logger -st "($(basename $0))" $$ "***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
     # Check if MONIT MANAGEMENT SYSTEM has been deployed
     # 检查MONIT MANAGEMENT SYSTEM是否已部署
     if [ -e "/opt/bin/monit" ]
     then
-        logger -st "($(basename $0))" $$ "***** MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED"
+        #
+        # Check if ${SERVICE_NAME} has been installed
+        # 检查${SERVICE_NAME}是否已安装
+        if [ ! -e "/opt/sbin/smbd" ]
+        then
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ${SERVICE_NAME} IS NOT INSTALLED"
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            exit 3
+        fi
         #
         # Stop SAMBA_SERVER service
         # 停止SAMBA_SERVER服务
-        /opt/bin/monit stop 'SAMBA_SERVER'
+        /opt/bin/monit stop "SAMBA_SERVER" > /dev/null 2>&1
+        #
+        # Wait until SAMBA_SERVER service is terminated
+        # 等待直至SAMBA_SERVER service被终止
+        while [ -n "$(pidof smbd)" ] || [ -n "$(pidof wsdd2)" ]
+        do
+            /opt/bin/sleep 5
+        done
+        #
+        # Configure dbus-daemon
+        # 配置dbus-daemon
+        /opt/bin/rm -f "/opt/etc/dbus-1/system.d/avahi-dbus.conf"
+        /opt/bin/mv -f "/opt/etc/dbus-1/system.d/avahi-dbus.conf.bak" "/opt/etc/dbus-1/system.d/avahi-dbus.conf"
+        /opt/bin/rm -f "${PRIVATE_ETC}/dbus/avahi-dbus.conf"
+        #
+        /opt/bin/rm -f "/opt/share/dbus-1/system.conf"
+        /opt/bin/mv -f "/opt/share/dbus-1/system.conf.bak" "/opt/share/dbus-1/system.conf"
+        /opt/bin/rm -f "${PRIVATE_ETC}/dbus/system.conf"
+        #
+        # Enable /opt/etc/init.d/S91smb
+        # 启用/opt/etc/init.d/S91smb
+        /opt/bin/mv -f "${PRIVATE_ETC}"/S*smb "/opt/etc/init.d"
+        #
+        # Configure samba
+        # 配置samba
+        /opt/bin/rm -f "/opt/etc/samba/smb.conf"
+        /opt/bin/mv -f "/opt/etc/samba/smb.conf.bak" "/opt/etc/samba/smb.conf"
+        #
+        /opt/bin/rm -f "${PRIVATE_ETC}/smb.conf.add"
+        #
+        /opt/bin/rm -f "/opt/etc/printcap"
+        /opt/bin/rm -rf "/opt/var/log/samba"
+        /opt/bin/rm -rf "/opt/var/log/cores/smbd"
+        /opt/bin/rm -f "/opt/var/log/log.smbd"
+        /opt/bin/rm -rf "/opt/var/lib/samba"
+        /opt/bin/rm -rf "/opt/var/cache/samba"
+        /opt/bin/rm -rf "/opt/var/run/samba"
         #
         # Uninstall samba
         # 卸载samba
@@ -88,45 +126,46 @@ then
         /opt/bin/opkg remove samba4-server
         /opt/bin/opkg remove samba4-libs
         #
+        # Configure wsdd2
+        # 配置wsdd2
+        /opt/bin/mv -f "${PRIVATE_ETC}"/S*wsdd2 "/opt/etc/init.d"
+        #
         # Uninstall wsdd2
         # 卸载wsdd2
         /opt/bin/opkg remove wsdd2
         #
         # Remove residue
         # 删除残留文件
-        /opt/bin/rm -rf /opt/etc/samba
-        #
-        /opt/bin/rm -f /opt/etc/printcap
-        /opt/bin/rm -rf /opt/var/log/samba
-        /opt/bin/rm -rf /opt/var/lib/samba
-        /opt/bin/rm -rf /opt/var/cache/samba
-        /opt/bin/rm -rf /opt/var/run/samba
-        /opt/bin/rm -rf ${PRIVATE_ROOT}
-        /opt/bin/rm -f ${SBL_SYS_TMP}/samba
-        #
-        #/opt/bin/mkdir /home/root/samba_share
+        /opt/bin/rm -rf "/opt/etc/samba"
         #
         # Configure monit
         # 配置monit
-        /opt/bin/rm -f ${ENTWARE_MONITD}/samba_server.on
+        /opt/bin/rm -f "${ENTWARE_MONITD}/samba_server.on"
+        /opt/bin/rm -f "${ENTWARE_MONITD}/samba_server"
         /opt/bin/monit reload
         #
-        logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 0
         #
     else
         # Do nothing but prompt the user
         # 如果MONIT MANAGEMENT SYSTEM未部署，则执行
-        logger -st "($(basename $0))" $$ "***** MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED *****"
-        logger -st "($(basename $0))" $$ "***** PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST *****"
-        logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 2
     fi
     #
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    logger -st "($(basename $0))" $$ "***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    logger -st "($(basename $0))" $$ "***** PLEASE ENABLE ENTWARE FIRST *****"
-    logger -st "($(basename $0))" $$ "***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+    #
+    exit 1
 fi
 #
 ########## END ##########
diff --git a/script_bootloader/usr/vlmcsd/bin/vlmcsd_install b/script_bootloader/usr/vlmcsd/bin/vlmcsd_install
--- a/script_bootloader/usr/vlmcsd/bin/vlmcsd_install
+++ b/script_bootloader/usr/vlmcsd/bin/vlmcsd_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,35 +14,35 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
 # 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
-ENTWARE_ETC=${USB_MOUNT_POINT}/etc
+ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
 #
 # ENTWARE_MONITD: The directory which contains all the configuration files used by monit
 # 设置自定义变量ENTWARE_MONITD为monit配置文件目录
-ENTWARE_MONITD=${ENTWARE_ETC}/monit.d
+ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 #
 # ENTWARE_DNSMASQD: The directory which contains all the configuration files used by dnsmasq
 # 设置自定义变量ENTWARE_DNSMASQD为dnsmasq配置文件目录
-ENTWARE_DNSMASQD=${ENTWARE_ETC}/dnsmasq.d
+ENTWARE_DNSMASQD="${ENTWARE_ETC}/dnsmasq.d"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/vlmcsd
+PRIVATE_ROOT="${SBL_SYS_USR}/vlmcsd"
 #
 # PRIVATE_ETC: The directory which contains all the configuration files related to this program
 # 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
+PRIVATE_ETC="${PRIVATE_ROOT}/etc"
 #
 # PRIVATE_USR: The directory which contains all the external software resources related to this program
 # 设置自定义变量PRIVATE_USR为此程序外部软件资源目录
-PRIVATE_USR=${PRIVATE_ROOT}/usr
+PRIVATE_USR="${PRIVATE_ROOT}/usr"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -50,14 +50,14 @@ SERVICE_NAME="VLMCSD"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-/opt/bin/echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+/opt/bin/echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -66,114 +66,113 @@ SERVICE_FUNCTION="INSTALLATION"
 #
 # Check if ENTWARE_ENABLE SERVICE has been loaded
 # 检查ENTWARE_ENABLE SERVICE是否已启用
-if [ $(which opkg) == "/opt/bin/opkg" ]
+if [ "$(which opkg)" == "/opt/bin/opkg" ]
 then
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS BEEN LOADED *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ENTWARE_ENABLE SERVICE HAS BEEN LOADED"
     #
     # Check if MONIT MANAGEMENT SYSTEM has been deployed
     # 检查MONIT MANAGEMENT SYSTEM是否已部署
     if [ -e "/opt/bin/monit" ]
     then
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED *****"
-        #
-        # Check the architecture of the ASUS Router
-        # 检查华硕路由器架构
-        ROUTER_ARCHITECTURE=$(/opt/bin/uname -m)
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: MONIT MANAGEMENT SYSTEM HAS BEEN DEPLOYED"
         #
         # Install vlmcsd according to the architecture of the ASUS Router
         # 根据路由器架构，自动安装适当版本的vlmcsd
-        if [ "${ROUTER_ARCHITECTURE}" == "armv7l" ] || [ "${ROUTER_ARCHITECTURE}" == "aarch64" ]
-        then
-            # Check if ${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static exist
-            # 检查文件${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static是否存在
-            if [ -e "${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static" ]
-            then
-                # Create two symbolic link files named ${PRIVATE_USR}/vlmcs and ${PRIVATE_USR}/vlmcsd
-                # 如果文件${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static存在，则执行
-                /opt/bin/cp -s ${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static ${PRIVATE_USR}/vlmcs
-                /opt/bin/cp -s ${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static ${PRIVATE_USR}/vlmcsd
+        case "$(/opt/bin/uname -m)" in
+            "aarch64" | "armv7l")
+                # Check if ${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static exist
+                # 检查文件${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static是否存在
+                if [ -e "${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static" ]
+                then
+                    # Create two symbolic link files named ${PRIVATE_USR}/vlmcs and ${PRIVATE_USR}/vlmcsd
+                    # 如果文件${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static存在，则执行
+                    /opt/bin/cp -fs "${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static" "${PRIVATE_USR}/vlmcs"
+                    /opt/bin/cp -fs "${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static" "${PRIVATE_USR}/vlmcsd"
+                    #
+                else
+                    # Do nothing but prompt the user
+                    # 如果文件${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static不存在，则执行
+                    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+                    #
+                    exit 4
+                fi
                 #
-            else
+                ;;
+            "mips")
+                # Check if ${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static exist
+                # 检查文件${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static是否存在
+                if [ -e "${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static" ]
+                then
+                    # Create two symbolic link files named ${PRIVATE_USR}/vlmcs and ${PRIVATE_USR}/vlmcsd
+                    # 如果文件${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static存在，则执行
+                    /opt/bin/cp -fs "${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static" "${PRIVATE_USR}/vlmcs"
+                    /opt/bin/cp -fs "${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static" "${PRIVATE_USR}/vlmcsd"
+                    #
+                else
+                    # Do nothing but prompt the user
+                    # 如果文件${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static不存在，则执行
+                    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+                    #
+                    exit 6
+                fi
+                #
+                ;;
+            *)
                 # Do nothing but prompt the user
-                # 如果文件${PRIVATE_USR}/vlmcsdmulti-armelv7-bcm47xx_53xx-openwrt-musl-static不存在，则执行
-                /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+                # 如果路由器架构不符合上述三种情况，则执行
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ROUTER ARCHITECTURE IS UNKNOWN"
                 #
-                exit 4
-            fi
-            #
-        elif [ "${ROUTER_ARCHITECTURE}" == "mips" ]
-        then
-            # Check if ${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static exist
-            # 检查文件${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static是否存在
-            if [ -e "${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static" ]
-            then
-                # Create two symbolic link files named ${PRIVATE_USR}/vlmcs and ${PRIVATE_USR}/vlmcsd
-                # 如果文件${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static存在，则执行
-                /opt/bin/cp -s ${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static ${PRIVATE_USR}/vlmcs
-                /opt/bin/cp -s ${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static ${PRIVATE_USR}/vlmcsd
-                #
-            else
-                # Do nothing but prompt the user
-                # 如果文件${PRIVATE_USR}/vlmcsdmulti-mips16el-asus-rt-n66u-uclibc-static不存在，则执行
-                /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
-                #
-                exit 6
-            fi
-            #
-        else
-            # Do nothing but prompt the user
-            # 如果路由器架构不符合上述三种情况，则执行
-            /opt/bin/echo "($(basename $0)): $$ ***** ROUTER ARCHITECTURE IS UNKNOWN *****"
-            /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
-            #
-            exit 3
-        fi
+                exit 3
+                ;;
+        esac
         #
-        # Check if ${PRIVATE_ETC}/dnsmasq.d exists
-        # 检查目录${PRIVATE_ETC}/dnsmasq.d是否存在
-        if [ ! -d "${PRIVATE_ETC}/dnsmasq.d" ]
-        then
-            # Create ${PRIVATE_ETC}/dnsmasq.d
-            # 创建目录${PRIVATE_ETC}/dnsmasq.d
-            /opt/bin/mkdir ${PRIVATE_ETC}/dnsmasq.d
-        fi
-        #
-        LOCAL_DOMAIN_A=$(/opt/bin/sed -n -e 's/^domain=//p' /etc/dnsmasq.conf)
-        LOCAL_DOMAIN_B=$(/opt/bin/sed -n -e 's/^domain=//p' ${ENTWARE_DNSMASQD}/dnsmasq_extended.conf)
+        # Configure dnsmasq.d
+        # 配置dnsmasq.d
+        LOCAL_DOMAIN_A="$(/opt/bin/sed -n -e 's/^domain=//p' /etc/dnsmasq.conf)"
+        LOCAL_DOMAIN_B="$(/opt/bin/sed -n -e 's/^domain=//p' "${ENTWARE_DNSMASQD}/dnsmasq_extended.conf")"
         #
         if [ -n "${LOCAL_DOMAIN_A}" ]
         then
+            if [ ! -d "${PRIVATE_ETC}/dnsmasq.d" ]
+            then
+                /opt/bin/mkdir "${PRIVATE_ETC}/dnsmasq.d"
+            fi
+            #
             LOCAL_DOMAIN="${LOCAL_DOMAIN_A}"
-            /opt/bin/echo -e "srv-host=_vlmcs._tcp.${LOCAL_DOMAIN},${ROUTER_MODEL}.${LOCAL_DOMAIN},1688,0,100" > ${PRIVATE_ETC}/dnsmasq.d/vlmcsd.conf
-            /opt/bin/cp ${PRIVATE_ETC}/dnsmasq.d/vlmcsd.conf ${ENTWARE_DNSMASQD}
+            /opt/bin/echo -e "srv-host=_vlmcs._tcp.${LOCAL_DOMAIN},${ROUTER_MODEL}.${LOCAL_DOMAIN},1688,0,100" > "${PRIVATE_ETC}/dnsmasq.d/vlmcsd.conf"
             #
         elif [ -n "${LOCAL_DOMAIN_B}" ]
         then
+            if [ ! -d "${PRIVATE_ETC}/dnsmasq.d" ]
+            then
+                /opt/bin/mkdir "${PRIVATE_ETC}/dnsmasq.d"
+            fi
+            #
             LOCAL_DOMAIN="${LOCAL_DOMAIN_B}"
-            /opt/bin/echo -e "srv-host=_vlmcs._tcp.${LOCAL_DOMAIN},${ROUTER_MODEL}.${LOCAL_DOMAIN},1688,0,100" > ${PRIVATE_ETC}/dnsmasq.d/vlmcsd.conf
-            /opt/bin/cp ${PRIVATE_ETC}/dnsmasq.d/vlmcsd.conf ${ENTWARE_DNSMASQD}
+            /opt/bin/echo -e "srv-host=_vlmcs._tcp.${LOCAL_DOMAIN},${ROUTER_MODEL}.${LOCAL_DOMAIN},1688,0,100" > "${PRIVATE_ETC}/dnsmasq.d/vlmcsd.conf"
             #
         else
-            /opt/bin/echo -ne "\033[1;41;37m***** ERROR: DOMAIN OF DNSMASQ IS MISSING *****\033[0m\n"
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: DOMAIN OF DNSMASQ IS MISSING"
+            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: KMS AUTO DISCOVERY CAN'T BE SET"
         fi
         #
         # Configure monit
         # 配置monit
-        /opt/bin/cp ${PRIVATE_ETC}/monit.d/vlmcsd ${ENTWARE_MONITD}/
-        /opt/bin/chmod 600 ${ENTWARE_MONITD}/vlmcsd
-        /opt/bin/mv ${ENTWARE_MONITD}/vlmcsd ${ENTWARE_MONITD}/vlmcsd.on
+        /opt/bin/cp -f "${PRIVATE_ETC}/monit.d/vlmcsd" "${ENTWARE_MONITD}"
+        /opt/bin/chmod 600 "${ENTWARE_MONITD}/vlmcsd"
+        /opt/bin/mv -f "${ENTWARE_MONITD}/vlmcsd" "${ENTWARE_MONITD}/vlmcsd.on"
         /opt/bin/monit reload
         #
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
         #
         exit 0
         #
     else
         # Do nothing but prompt the user
         # 如果MONIT MANAGEMENT SYSTEM未部署，则执行
-        /opt/bin/echo "($(basename $0)): $$ ***** MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST *****"
-        /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: MONIT MANAGEMENT SYSTEM HAS NOT BEEN DEPLOYED"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE DEPLOY MONIT MANAGEMENT SYSTEM FIRST"
+        /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
         #
         exit 2
     fi
@@ -181,9 +180,9 @@ then
 else
     # Do nothing but prompt the user
     # 如果ENTWARE_ENABLE SERVICE未启用，则执行
-    /opt/bin/echo "($(basename $0)): $$ ***** ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** PLEASE ENABLE ENTWARE FIRST *****"
-    /opt/bin/echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENTWARE_ENABLE SERVICE HAS NOT BEEN LOADED"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: PLEASE ENABLE ENTWARE FIRST"
+    /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     exit 1
 fi
