Update sys_addons_pre_dependency

diff --git a/script_bootloader/usr/entware/bin/entware_install b/script_bootloader/usr/entware/bin/entware_install
--- a/script_bootloader/usr/entware/bin/entware_install
+++ b/script_bootloader/usr/entware/bin/entware_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,19 +14,19 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/entware
+PRIVATE_ROOT="${SBL_SYS_USR}/entware"
 #
 # PRIVATE_ETC: The directory which contains all the configuration files related to this program
 # 设置自定义变量PRIVATE_ETC为此程序配置文件目录
-PRIVATE_ETC=${PRIVATE_ROOT}/etc
+PRIVATE_ETC="${PRIVATE_ROOT}/etc"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -34,7 +34,7 @@ SERVICE_NAME="ENTWARE"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 # FILES_TO_COPY: The list of files that should be copied
 # 设置自定义变量FILES_TO_COPY为待复制文件列表
@@ -45,7 +45,7 @@ FILES_TO_COPY="${PRIVATE_ETC}/files_to_copy.autosave"
 #
 ########## NOTIFICATION ##########
 #
-echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -58,11 +58,11 @@ if [ -L "/opt" ]
 then
     # OPT_TARGET: The target of the symbolic link /opt
     # 设置自定义变量OPT_TARGET为符号链接文件/opt的目标
-    OPT_TARGET=$(ls -al /opt | sed -E -n -e 's/.*->[[:space:]]*([^[:space:]]*)/\/\1/p')
+    OPT_TARGET="$(ls -al "/opt" | sed -E -n -e 's#.*->[[:space:]]+([^[:space:]]+.*$)#/\1#p')"
     #
     # Create symbolic link file ${OPT_TARGET}
     # 创建符号链接文件${OPT_TARGET}
-    ln -sf ${USB_MOUNT_POINT} ${OPT_TARGET}
+    ln -fs "${USB_MOUNT_POINT}" "${OPT_TARGET}"
     #
     sleep 5
     #
@@ -71,24 +71,38 @@ then
     # If it is a directory, then copy all files except symbolic link files in /opt to ${USB_MOUNT_POINT} and mount ${USB_MOUNT_POINT} to /opt
     # 如果是目录，则将目录/opt下全部非符号链接文件复制至目录${USB_MOUNT_POINT}，之后挂载目录${USB_MOUNT_POINT}至目录/opt
     #
-    mkdir ${PRIVATE_ETC}
-    ls -al /opt/ | sed -E -n -e 's/^[^l[:space:]]{10}.*[[:space:]]+(.*[^.]$)/\1/p' > ${FILES_TO_COPY}
-    sed -i "s/^/\/opt\//" ${FILES_TO_COPY}
-    cp -r $(cat ${FILES_TO_COPY}) ${USB_MOUNT_POINT}
-    echo "($(basename $0)): $$ ***** FILES IN /opt HAVE BEEN COPIED *****"
+    mkdir "${PRIVATE_ETC}"
+    ls -al "/opt" | sed -E -n -e 's/^[^l[:space:]]{10}.*[[:digit:]:]+[[:space:]]+(.*[^.]$)/\1/p' > "${FILES_TO_COPY}"
+    sed -i 's#^#/opt/#' "${FILES_TO_COPY}"
+    cp -f "${FILES_TO_COPY}" "${FILES_TO_COPY}.stack"
+    #
+    while [ 1 ]
+    do
+        STACK_TOP="$(head -n 1 "${FILES_TO_COPY}.stack")"
+        if [ -n "${STACK_TOP}" ]
+        then
+            cp -rf "${STACK_TOP}" "${USB_MOUNT_POINT}"
+            sed -i '1d' "${FILES_TO_COPY}.stack"
+        else
+            rm -f "${FILES_TO_COPY}.stack"
+            break
+        fi
+    done
+    #
+    echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: FILES IN /opt ARE COPIED"
     #
     # Mount the USB flash drive to /opt
     # 挂载U盘至目录/opt
-    mount ${USB_MOUNT_POINT} /opt
+    mount "${USB_MOUNT_POINT}" "/opt"
     #
     sleep 5
     #
 else
     # Do nothing but prompt the user
     # 如果/opt的类型不符合上述两种情况，则执行
-    echo "($(basename $0)): $$ ***** TYPE OF /opt IS UNKNOWN *****"
-    echo "($(basename $0)): $$ ***** ENVIRONMENT FOR ENTWARE CAN'T BE SET *****"
-    echo "($(basename $0)): $$ ***** ${SERVICE_NAME}_${SERVICE_FUNCTION} SERVICE HAS NOT BEEN LOADED *****"
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: TYPE OF /opt IS UNKNOWN"
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ENVIRONMENT FOR ENTWARE CAN'T BE SET"
+    echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     exit 1
 fi
@@ -100,24 +114,48 @@ fi
 #
 # Install Entware according to the architecture of the ASUS Router
 # 根据路由器架构，自动安装适当版本的Entware
-case $(uname -m) in
+case "$(uname -m)" in
     "aarch64")
-        wget -O - http://bin.entware.net/aarch64-k3.10/installer/generic.sh | sh
-        echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        wget -O - "http://bin.entware.net/aarch64-k3.10/installer/generic.sh" | sh
+        #
+        if [ ${?} -eq 0 ]
+        then
+            echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        else
+            echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            exit 2
+        fi
         ;;
     "armv7l")
-        wget -O - http://bin.entware.net/armv7sf-k2.6/installer/generic.sh | sh
-        echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        wget -O - "http://bin.entware.net/armv7sf-k2.6/installer/generic.sh" | sh
+        #
+        if [ ${?} -eq 0 ]
+        then
+            echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        else
+            echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            exit 2
+        fi
         ;;
     "mips")
-        wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | sh
-        echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+        wget -O - "http://pkg.entware.net/binaries/mipsel/installer/installer.sh" | sh
+        #
+        if [ ${?} -eq 0 ]
+        then
+            echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        else
+            echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            #
+            exit 2
+        fi
         ;;
     *)
         # Do nothing but prompt the user
         # 如果路由器架构不符合上述三种情况，则执行
-        echo "($(basename $0)): $$ ***** ROUTER ARCHITECTURE IS UNKNOWN *****"
-        echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS NOT BEEN COMPLETE *****"
+        echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ROUTER ARCHITECTURE IS UNKNOWN"
+        echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
         #
         exit 2
         ;;
@@ -128,35 +166,30 @@ esac
 #
 ########## COPY FILES FROM FIRMWARE ##########
 #
-echo "($(basename $0)): $$ ***** COPY FILES FROM FIRMWARE TO USB FLASH DRIVE *****"
+cp -f "/etc/passwd" "${USB_MOUNT_POINT}/etc/passwd_from_firmware"
+cp -f "/etc/shadow" "${USB_MOUNT_POINT}/etc/shadow_from_firmware"
 #
-cp /etc/passwd ${USB_MOUNT_POINT}/etc/passwd_from_firmware
-cp /etc/shadow ${USB_MOUNT_POINT}/etc/shadow_from_firmware
+echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: FILES FROM FIRMWARE ARE COPIED"
 #
 ########## END ##########
 #
 #
 ########## COPY HOME ##########
 #
-echo "($(basename $0)): $$ ***** COPY HOME TO USB FLASH DRIVE *****"
-#
 # Check if HOME is already in the USB flash drive
-# 检查目录${USB_MOUNT_POINT}/home/root/是否存在
-if [ ! -d "${USB_MOUNT_POINT}/home/root/" ]
+# 检查目录${USB_MOUNT_POINT}/home/root是否存在
+if [ ! -d "${USB_MOUNT_POINT}/home/root" ]
 then
-    # Copy /tmp/home/root to ${USB_MOUNT_POINT}/home/
-    # 如果目录${USB_MOUNT_POINT}/home/root/不存在，则执行
-    cp -r /tmp/home/root ${USB_MOUNT_POINT}/home/
-    echo "($(basename $0)): $$ ***** HOME HAS BEEN COPIED *****"
-    #
-    exit 0
-    #
+    # Copy /tmp/home/root to ${USB_MOUNT_POINT}/home
+    # 如果目录${USB_MOUNT_POINT}/home/root不存在，则执行
+    cp -rf "/tmp/home/root" "${USB_MOUNT_POINT}/home"
+    echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: HOME IS COPIED"
 else
     # Do nothing but prompt the user
-    # 如果目录${USB_MOUNT_POINT}/home/root/存在，则执行
-    echo "($(basename $0)): $$ ***** HOME EXISTS *****"
-    #
-    exit 0
+    # 如果目录${USB_MOUNT_POINT}/home/root存在，则执行
+    echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: HOME EXISTS"
 fi
+#
+exit 0
 #
 ########## END ##########
diff --git a/script_bootloader/usr/swap/bin/swap_install b/script_bootloader/usr/swap/bin/swap_install
--- a/script_bootloader/usr/swap/bin/swap_install
+++ b/script_bootloader/usr/swap/bin/swap_install
@@ -2,7 +2,7 @@
 #
 ########## CHECK ASUS ROUTER MODEL ##########
 #
-ROUTER_MODEL=$(nvram get model)
+ROUTER_MODEL="$(nvram get model)"
 #
 ########## END ##########
 #
@@ -14,19 +14,23 @@ ROUTER_MODEL=$(nvram get model)
 #
 # USB_MOUNT_POINT: The mount point of the USB flash drive
 # 设置自定义变量USB_MOUNT_POINT为U盘挂载点
-USB_MOUNT_POINT=$(nvram get script_usbmount | sed 's/\/script_bootloader.*//')
+USB_MOUNT_POINT="$(nvram get script_usbmount | sed 's/\/script_bootloader.*//')"
 #
 # SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
 # 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
-SBL_SYS_USR=${USB_MOUNT_POINT}/script_bootloader/usr
+SBL_SYS_USR="${USB_MOUNT_POINT}/script_bootloader/usr"
 #
 # PRIVATE_ROOT: The root directory for this program
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
-PRIVATE_ROOT=${SBL_SYS_USR}/swap
+PRIVATE_ROOT="${SBL_SYS_USR}/swap"
+#
+# PRIVATE_BIN: The directory which contains all the executable files related to this program
+# 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
+PRIVATE_BIN="${PRIVATE_ROOT}/bin"
 #
 # PRIVATE_VAR: The directory which contains all the variable files related to this program
 # 设置自定义变量PRIVATE_VAR为此程序可变文件目录
-PRIVATE_VAR=${PRIVATE_ROOT}/var
+PRIVATE_VAR="${PRIVATE_ROOT}/var"
 #
 # NAME OF THE SERVICE
 # 服务名称
@@ -34,14 +38,14 @@ SERVICE_NAME="SWAP"
 #
 # FUNCTION OF THE SERVICE
 # 服务功能
-SERVICE_FUNCTION="INSTALLATION"
+SERVICE_FUNCTION="INSTALL"
 #
 ########## END ##########
 #
 #
 ########## NOTIFICATION ##########
 #
-echo "($(basename $0)): $$ *--------- ${SERVICE_NAME} ON ${ROUTER_MODEL} ${SERVICE_FUNCTION} ---------*"
+echo -e "($(basename $0)): $$ *--------- ${SERVICE_FUNCTION} ${SERVICE_NAME} ON ${ROUTER_MODEL} ---------*"
 #
 ########## END ##########
 #
@@ -54,45 +58,41 @@ if [ ! -d "${PRIVATE_VAR}" ]
 then
     # Create directory ${PRIVATE_VAR}
     # 如果目录${PRIVATE_VAR}不存在，则执行
-    mkdir ${PRIVATE_VAR}
+    mkdir "${PRIVATE_VAR}"
 fi
 #
 # Check if ${PRIVATE_VAR}/swapfile.var exists
 # 检查文件${PRIVATE_VAR}/swapfile.var是否存在
 if [ -e "${PRIVATE_VAR}/swapfile.var" ]
 then
-    echo "($(basename $0)): $$ ***** ${PRIVATE_VAR}/swapfile.var EXISTS *****"
+    echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ${PRIVATE_VAR}/swapfile.var EXISTS"
     #
     # Do nothing but prompt the user
     # 如果文件${PRIVATE_VAR}/swapfile.var存在，则执行
-    echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
+    echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
     #
     exit 0
     #
 else
     # Create ${PRIVATE_VAR}/swapfile.var
     # 如果文件${PRIVATE_VAR}/swapfile.var不存在，则创建${PRIVATE_VAR}/swapfile.var
-    echo "($(basename $0)): $$ ***** UNABLE TO LOCATE ${PRIVATE_VAR}/swapfile.var *****"
-    echo "($(basename $0)): $$ ***** CREATE ${PRIVATE_VAR}/swapfile.var *****"
+    echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: CREATE ${PRIVATE_VAR}/swapfile.var"
     #
-    # Set the size of swapfile.var to 256M
-    # 设定文件swapfile.var的大小为256M
-    #dd if=/dev/zero of=${PRIVATE_VAR}/swapfile.var bs=1024 count=262148
+    "${PRIVATE_BIN}/swap_configure"
     #
-    # Set the size of swapfile.var to 512M
-    # 设定文件swapfile.var的大小为512M
-    dd if=/dev/zero of=${PRIVATE_VAR}/swapfile.var bs=1024 count=524292
-    #
-    # Set the size of swapfile.var to 1G
-    # 设定文件swapfile.var的大小为1G
-    #dd if=/dev/zero of=${PRIVATE_VAR}/swapfile.var bs=1024 count=1024004
-    #
-    mkswap -L ASUS_SWAP ${PRIVATE_VAR}/swapfile.var
-    chmod 600 ${PRIVATE_VAR}/swapfile.var
-    echo "($(basename $0)): $$ ***** ${PRIVATE_VAR}/swapfile.var HAS BEEN CREATED *****"
-    echo "($(basename $0)): $$ ***** ${SERVICE_FUNCTION} HAS BEEN COMPLETE *****"
-    #
-    exit 0
+    if [ ${?} -eq 0 ]
+    then
+        echo -e "($(basename $0)): $$ \033[1;44;37mINFO\033[0m: ${PRIVATE_VAR}/swapfile.var IS CREATED"
+        echo -e "($(basename $0)): $$ \033[1;42;37mSUCCESS\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 0
+        #
+    else
+        echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: ${PRIVATE_VAR}/swapfile.var CAN'T BE CREATED"
+        echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+        #
+        exit 1
+    fi
 fi
 #
 ########## END ##########
