Add offline capability

diff --git a/script_bootloader/usr/caddy/bin/caddy_install b/script_bootloader/usr/caddy/bin/caddy_install
--- a/script_bootloader/usr/caddy/bin/caddy_install
+++ b/script_bootloader/usr/caddy/bin/caddy_install
@@ -44,6 +44,10 @@ SBL_SITE="${USB_MOUNT_POINT}/www"
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
 PRIVATE_ROOT="${SBL_SYS_USR}/caddy"
 #
+# PRIVATE_ALTERNATIVE: The directory which contains all the alternatives
+# 设置自定义变量PRIVATE_ALTERNATIVE为此程序备用文件目录
+PRIVATE_ALTERNATIVE="${PRIVATE_ROOT}/alternative"
+#
 # PRIVATE_BIN: The directory which contains all the executable files related to this program
 # 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
 PRIVATE_BIN="${PRIVATE_ROOT}/bin"
@@ -118,20 +122,32 @@ then
         # 删除遗留的caddy包
         /opt/bin/rm -f "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
         #
-        # Download caddy
-        # 下载caddy
-        /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -O "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" "${DOWNLOAD_LINK}"
-        #
-        # Check if ${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz exists
-        # 检查文件${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz是否存在
-        if [ ! -s "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" ]
+        # Check if ${PRIVATE_ALTERNATIVE}/version exists
+        # 检查文件${PRIVATE_ALTERNATIVE}/version是否存在
+        if [ -e "${PRIVATE_ALTERNATIVE}/version" ]
         then
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            # Prepare to install offline
+            # 准备离线安装
+            LATEST_VERSION="$(/opt/bin/head -n 1 "${PRIVATE_ALTERNATIVE}/version")"
+            /opt/bin/cp -f "${PRIVATE_ALTERNATIVE}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" "${PRIVATE_BIN}"
             #
-            /opt/bin/rm -f "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
+        else
+            # Download caddy
+            # 下载caddy
+            /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -O "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" "${DOWNLOAD_LINK}"
             #
-            exit 5
+            # Check if ${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz exists
+            # 检查文件${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz是否存在
+            if [ ! -s "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" ]
+            then
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+                #
+                /opt/bin/rm -f "${PRIVATE_BIN}/caddy_${LATEST_VERSION}_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
+                #
+                exit 5
+            fi
+            #
         fi
         #
         # Create directory ${PRIVATE_USR}
diff --git a/script_bootloader/usr/overture/bin/overture_install b/script_bootloader/usr/overture/bin/overture_install
--- a/script_bootloader/usr/overture/bin/overture_install
+++ b/script_bootloader/usr/overture/bin/overture_install
@@ -40,6 +40,10 @@ ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
 PRIVATE_ROOT="${SBL_SYS_USR}/overture"
 #
+# PRIVATE_ALTERNATIVE: The directory which contains all the alternatives
+# 设置自定义变量PRIVATE_ALTERNATIVE为此程序备用文件目录
+PRIVATE_ALTERNATIVE="${PRIVATE_ROOT}/alternative"
+#
 # PRIVATE_BIN: The directory which contains all the executable files related to this program
 # 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
 PRIVATE_BIN="${PRIVATE_ROOT}/bin"
@@ -122,20 +126,32 @@ then
         # 删除遗留的overture包
         /opt/bin/rm -f "${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip"
         #
-        # Download overture
-        # 下载overture
-        /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
-        #
-        # Check if ${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip exists
-        # 检查文件${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip是否存在
-        if [ ! -s "${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip" ]
+        # Check if ${PRIVATE_ALTERNATIVE}/version exists
+        # 检查文件${PRIVATE_ALTERNATIVE}/version是否存在
+        if [ -e "${PRIVATE_ALTERNATIVE}/version" ]
         then
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            # Prepare to install offline
+            # 准备离线安装
+            LATEST_VERSION="$(/opt/bin/head -n 1 "${PRIVATE_ALTERNATIVE}/version")"
+            /opt/bin/cp -f "${PRIVATE_ALTERNATIVE}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip" "${PRIVATE_BIN}"
             #
-            /opt/bin/rm -f "${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip"
+        else
+            # Download overture
+            # 下载overture
+            /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
             #
-            exit 5
+            # Check if ${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip exists
+            # 检查文件${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip是否存在
+            if [ ! -s "${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip" ]
+            then
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+                #
+                /opt/bin/rm -f "${PRIVATE_BIN}/overture-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}.zip"
+                #
+                exit 5
+            fi
+            #
         fi
         #
         # Create directory overture
diff --git a/script_bootloader/usr/syncthing/bin/syncthing_install b/script_bootloader/usr/syncthing/bin/syncthing_install
--- a/script_bootloader/usr/syncthing/bin/syncthing_install
+++ b/script_bootloader/usr/syncthing/bin/syncthing_install
@@ -40,6 +40,10 @@ ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
 PRIVATE_ROOT="${SBL_SYS_USR}/syncthing"
 #
+# PRIVATE_ALTERNATIVE: The directory which contains all the alternatives
+# 设置自定义变量PRIVATE_ALTERNATIVE为此程序备用文件目录
+PRIVATE_ALTERNATIVE="${PRIVATE_ROOT}/alternative"
+#
 # PRIVATE_BIN: The directory which contains all the executable files related to this program
 # 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
 PRIVATE_BIN="${PRIVATE_ROOT}/bin"
@@ -86,6 +90,14 @@ esac
 # 设置自定义变量DOWNLOAD_LINK为最新版syncthing的下载链接
 DOWNLOAD_LINK="https://github.com/syncthing/syncthing/releases/download/${LATEST_VERSION}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz"
 #
+# ADMINUSER: The administrator of the router
+# 设置环境变量ADMINUSER为路由器管理页面的登陆帐号
+ADMINUSER="$(nvram get sbl_username)"
+#
+# ADMINPASSWORD: The administrator's password of the router
+# 设置环境变量ADMINPASSWORD为路由器管理页面的登陆密码
+ADMINPASSWORD="$(nvram get sbl_password)"
+#
 ########## END ##########
 #
 #
@@ -114,20 +126,32 @@ then
         # 删除遗留的syncthing包
         /opt/bin/rm -f "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz"
         #
-        # Download syncthing
-        # 下载syncthing
-        /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
-        #
-        # Check if ${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz exists
-        # 检查文件${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz是否存在
-        if [ ! -s "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz" ]
+        # Check if ${PRIVATE_ALTERNATIVE}/version exists
+        # 检查文件${PRIVATE_ALTERNATIVE}/version是否存在
+        if [ -e "${PRIVATE_ALTERNATIVE}/version" ]
         then
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            # Prepare to install offline
+            # 准备离线安装
+            LATEST_VERSION="$(/opt/bin/head -n 1 "${PRIVATE_ALTERNATIVE}/version")"
+            /opt/bin/cp -f "${PRIVATE_ALTERNATIVE}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz" "${PRIVATE_BIN}"
             #
-            /opt/bin/rm -f "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz"
+        else
+            # Download syncthing
+            # 下载syncthing
+            /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
             #
-            exit 5
+            # Check if ${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz exists
+            # 检查文件${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz是否存在
+            if [ ! -s "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz" ]
+            then
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+                #
+                /opt/bin/rm -f "${PRIVATE_BIN}/syncthing-${OPERATING_SYSTEM}-${ROUTER_ARCHITECTURE}-${LATEST_VERSION}.tar.gz"
+                #
+                exit 5
+            fi
+            #
         fi
         #
         # Unzip syncthing package
@@ -147,7 +171,11 @@ then
         "${PRIVATE_USR}/syncthing" -generate="${PRIVATE_ETC}"
         /opt/bin/cp -f "${PRIVATE_ETC}/config.xml" "${PRIVATE_ETC}/config.xml.bak"
         /opt/bin/sed -i 's/127.0.0.1:8384/0.0.0.0:8384/' "${PRIVATE_ETC}/config.xml"
+        ADMINPASSWORD_ENCRYPTED="$(/opt/bin/bcrypt-tool hash "${ADMINPASSWORD}" 10)"
+        /opt/bin/sed -i '/0.0.0.0:8384/a\        <user>'"${ADMINUSER}"'</user>\n        <password>'"${ADMINPASSWORD_ENCRYPTED}"'</password>' "${PRIVATE_ETC}/config.xml"
         /opt/bin/sed -i 's/<startBrowser>true/<startBrowser>false/' "${PRIVATE_ETC}/config.xml"
+        /opt/bin/sed -i 's/<crashReportingEnabled>true/<crashReportingEnabled>false/' "${PRIVATE_ETC}/config.xml"
+        /opt/bin/sed -i 's/<urAccepted>0/<urAccepted>-1/' "${PRIVATE_ETC}/config.xml"
         /opt/bin/sed -i 's/<autoUpgradeIntervalH>12/<autoUpgradeIntervalH>0/' "${PRIVATE_ETC}/config.xml"
         #
         # Configure monit
